In [1]:
# lowkey just copy what i did in exposed_mutations but get the middle + last nucleotide
#i.e. get mutational contexts for SNPs -> dinucleotide context

In [1]:
import pandas as pd
import pysam
import os

In [2]:
#nucleosomes
def load_nuc1(nuc_path):
    colnames = ["chr", "start", "end", "NAME", "col5", "col6", "col7", "col8", "phase"]
    df = pd.read_csv(nuc_path, sep="\t", header=None)
    df.columns = colnames
    return df

def load_nuc2(nuc_path):
    colnames = ["chr", "start", "end", "NAME", "col5", "col6", "col7", "col8", "col9", "col10", "col11", "col12", "col13", "col14", "col15", "col16", "col17","phase"]
    df = pd.read_csv(nuc_path, sep="\t", header=None)
    df.columns = colnames
    return df

#plusone nucs
plusone_nuc_phase0 = load_nuc1("/home/ubuntu/honors_research/peak_align/reference_files/+1_Nuc_References/+1_phase0.bed")
plusone_nuc_phase1 = load_nuc1("/home/ubuntu/honors_research/peak_align/reference_files/+1_Nuc_References/+1_phase1.bed")
plusone_nuc_phase2 = load_nuc1("/home/ubuntu/honors_research/peak_align/reference_files/+1_Nuc_References/+1_phase2.bed")
plusone_nuc_phase3 = load_nuc1("/home/ubuntu/honors_research/peak_align/reference_files/+1_Nuc_References/+1_phase3.bed")
plusone_nuc_phase4 = load_nuc1("/home/ubuntu/honors_research/peak_align/reference_files/+1_Nuc_References/+1_phase4.bed")
plusone_nuc_phase5 = load_nuc1("/home/ubuntu/honors_research/peak_align/reference_files/+1_Nuc_References/+1_phase5.bed")
plusone_nuc_phase6 = load_nuc1("/home/ubuntu/honors_research/peak_align/reference_files/+1_Nuc_References/+1_phase6.bed")
plusone_nuc_phase7 = load_nuc1("/home/ubuntu/honors_research/peak_align/reference_files/+1_Nuc_References/+1_phase7.bed")
plusone_nuc_phase8 = load_nuc1("/home/ubuntu/honors_research/peak_align/reference_files/+1_Nuc_References/+1_phase8.bed")
plusone_nuc_phase9 = load_nuc1("/home/ubuntu/honors_research/peak_align/reference_files/+1_Nuc_References/+1_phase9.bed")
plusone_nuc = pd.concat([plusone_nuc_phase0, plusone_nuc_phase1, plusone_nuc_phase2, plusone_nuc_phase3, plusone_nuc_phase4, plusone_nuc_phase5, plusone_nuc_phase6, plusone_nuc_phase7, plusone_nuc_phase8, plusone_nuc_phase9], ignore_index=True)

#plustwo nucs
plustwo_nuc_phase0 = load_nuc2("/home/ubuntu/honors_research/peak_align/reference_files/+2_Nuc_References/+2_phase0.bed")
plustwo_nuc_phase1 = load_nuc2("/home/ubuntu/honors_research/peak_align/reference_files/+2_Nuc_References/+2_phase1.bed")
plustwo_nuc_phase2 = load_nuc2("/home/ubuntu/honors_research/peak_align/reference_files/+2_Nuc_References/+2_phase2.bed")
plustwo_nuc_phase3 = load_nuc2("/home/ubuntu/honors_research/peak_align/reference_files/+2_Nuc_References/+2_phase3.bed")
plustwo_nuc_phase4 = load_nuc2("/home/ubuntu/honors_research/peak_align/reference_files/+2_Nuc_References/+2_phase4.bed")
plustwo_nuc_phase5 = load_nuc2("/home/ubuntu/honors_research/peak_align/reference_files/+2_Nuc_References/+2_phase5.bed")
plustwo_nuc_phase6 = load_nuc2("/home/ubuntu/honors_research/peak_align/reference_files/+2_Nuc_References/+2_phase6.bed")
plustwo_nuc_phase7 = load_nuc2("/home/ubuntu/honors_research/peak_align/reference_files/+2_Nuc_References/+2_phase7.bed")
plustwo_nuc_phase8 = load_nuc2("/home/ubuntu/honors_research/peak_align/reference_files/+2_Nuc_References/+2_phase8.bed")
plustwo_nuc_phase9 = load_nuc2("/home/ubuntu/honors_research/peak_align/reference_files/+2_Nuc_References/+2_phase9.bed")
plustwo_nuc = pd.concat([plustwo_nuc_phase0, plustwo_nuc_phase1, plustwo_nuc_phase2, plustwo_nuc_phase3, plustwo_nuc_phase4, plustwo_nuc_phase5, plustwo_nuc_phase6, plustwo_nuc_phase7, plustwo_nuc_phase8, plustwo_nuc_phase9], ignore_index=True)

In [4]:
plustwo_nuc

,chr,start,end,NAME,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15,col16,col17,phase
0,chr1,2229073,2229073,chr1_2229073_2229073,222,+,0.183908,sameYR_lowWS,chr1,2228033,2228033,chr1_2228033_2228033,999,+,816,-3_CT_-2_-1_CA_0_1_GT_2_c_main_NFR_First_Refer...,1040,0
1,chr1,3857730,3857730,chr1_3857730_3857730,158,+,0.119047,sameYR_lowWS,chr1,3857460,3857460,chr1_3857460_3857460,131,+,110,-3_TG_-2_-1_TA_0_1_GT_2_c_main_NFR_First_Refer...,270,0
2,chr1,6393995,6393995,chr1_6393995_6393995,346,+,0.140000,sameYR_lowWS,chr1,6393535,6393535,chr1_6393535_6393535,158,+,112,-3_GC_-2_-1_CA_0_1_AG_2_c_main_NFR_First_Diver...,460,0
3,chr1,9234225,9234225,chr1_9234225_9234225,277,-,0.141414,sameYR_lowWS,chr1,9234605,9234605,chr1_9234605_9234605,28,-,101,-3_TC_-2_-1_CC_0_1_TT_2_c_main_NFR_First_Diver...,380,0
4,chr1,11011982,11011982,chr1_11011982_11011982,149,-,0.107345,sameYR_lowWS,chr1,11012272,11012272,chr1_11012272_11012272,87,-,139,-3_GG_-2_-1_GA_0_1_TC_2_c_main_NFR_First_Refer...,290,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45440,chr9,93096676,93096676,chr9_93096676_93096676,122,+,0.000000,lessDNAencode,chr9,93096217,93096217,chr9_93096217_93096217,110,+,335,-3_AG_-2_-1_CC_0_1_AA_2_c_main_NFR_First_Diver...,459,9
45441,chr9,129024363,129024363,chr9_129024363_129024363,187,+,0.000000,lessDNAencode,chr9,129023924,129023924,chr9_129023924_129023924,6,+,3,-3_AT_-2_-1_TA_0_1_CC_2_c_main_NDR_First_Singl...,439,9
45442,chrX,103554656,103554656,chrX_103554656_103554656,196,-,0.000000,lessDNAencode,chrX,103554945,103554945,chrX_103554945_103554945,20,-,91,-3_TT_-2_-1_TA_0_1_AT_2_c_main_NFR_First_Singl...,289,9
45443,chrX,119333906,119333906,chrX_119333906_119333906,387,+,0.000000,lessDNAencode,chrX,119332947,119332947,chrX_119332947_119332947,26,+,570,-3_GG_-2_-1_CA_0_1_AC_2_c_main_NFR_First_Singl...,959,9
45444,chrX,154411126,154411126,chrX_154411126_154411126,207,-,0.000000,lessDNAencode,chrX,154411475,154411475,chrX_154411475_154411475,190,-,140,-3_GG_-2_-1_CA_0_1_GC_2_c_main_NFR_First_Refer...,349,9

New dinucleotide categories

In [5]:
#what i want to do: take a 150bp window at the dyad (column name is 125) -> get the nucleotide sequence for that window
#then take a 5bp window starting from the beginning of the 150bp window
# look at at the first two and last two positions of the window (ignore middle) -> categorize these bases as S (GC) or W (AT)
# create a list/variable that has categories that are: WW-WW, SS-SS, WW-SW or WW-WS, SW-WW or WS-WW, SW-SW, SW-SS or WS-SS, SS-SW or SS-WS
# categorize nucleotides into one of those categories based on which category has the lowest mismatch (based on the nucleotides in each 5bp windows -> so like take each 5bp window + figure out which dinucleotide category it would fall into -> then figure out which category has the lowest mismatch -> assign that category to the nucleosome)

In [3]:
#load reference genome
reference_genome = pysam.FastaFile("/home/ubuntu/honors_research/hg38.fa")

# get the 150bp window sequence at the dyad (add this to a new column in the dataframe)
def get_dyad_sequence(df, reference_genome):
    sequences = []
    for index, row in df.iterrows():
        chrom = row["chr"]
        dyad_position = row["start"] + 125
        start = dyad_position - 75
        end = dyad_position + 75
        sequence = reference_genome.fetch(chrom, start, end).upper()
        sequences.append(sequence)
    df["dyad_sequence"] = sequences
    return df

plusone_nuc = get_dyad_sequence(plusone_nuc, reference_genome)
plustwo_nuc = get_dyad_sequence(plustwo_nuc, reference_genome)

In [18]:
plusone_nuc

,chr,start,end,NAME,col5,col6,col7,col8,phase,dyad_sequence,dinuc_category
0,chr1,999644,999644,chr1_999644_999644,450,-,0.051948,YRWS,0,TTTTCTGAGGGCGTCCAGGATGAGGGTTTTGAGCTGAGCGAGGCTC...,WW-WW + SS-SS
1,chr1,1013609,1013609,chr1_1013609_1013609,140,+,0.202247,YRWS,0,GGTGCAGGGAGAGCGGAGCTGCTCAGAGCTTGGCCAGGTTCTAAGT...,WS-WS + SW-SW
2,chr1,1020730,1020730,chr1_1020730_1020730,610,+,0.253522,lowYR_sameWS,0,GAGAAAAAGGGGCGCACAGCCTGAGCTCCCAACCCCGGGAGCCAGG...,WW-WW + SS-SS
3,chr1,1185518,1185518,chr1_1185518_1185518,130,-,0.168142,lessDNAencode,0,CTTTCTGTGGGGGTACCTGTGGGGTACTTCAAACAGCCCTAGCAGC...,WW-WS + SS-SW
4,chr1,1231866,1231866,chr1_1231866_1231866,230,+,0.129033,antiYR_antiWS,0,CCGAGGACCGGAGCGAAGCGTCAGTGACGCCGCCAACGGGCCCGGA...,WW-WW + SS-SS
...,...,...,...,...,...,...,...,...,...,...,...
45543,chrX,154479147,154479147,chrX_154479147_154479147,79,+,0.130435,YRWS,9,CAGTCGGTCCGGCCCCAGGAAGCCAACCCTGACGGGGCTTTTGAAG...,WW-WW + SS-SS
45544,chrX,154547463,154547463,chrX_154547463_154547463,99,-,0.000000,antiYR_antiWS,9,CGGAGCGGGATGCGGCCCTACCGCGGCCTCACACTTCTCGCCGGCT...,WW-WW + SS-SS
45545,chrX,154801954,154801954,chrX_154801954_154801954,119,+,0.142857,YRWS,9,TTTCTCAGGTGAAATTATAACTAGTCAGAAGCAGAGTCAGTGATCA...,WW-SW + SS-WS
45546,chrX,154805749,154805749,chrX_154805749_154805749,139,+,0.134615,sameYR_lowWS,9,GGAAATCAGAATCGGCCGGCTTAGTGGAGTTCAAAAGATGTAGGTG...,WS-WS + SW-SW
45547,chrX,155881108,155881108,chrX_155881108_155881108,89,-,0.225000,lessDNAencode,9,GAACGAACGTGAAACACTCAGTGATACTCCAACCGGAACTACTACT...,WS-SW + SW-WS

In [4]:
#getting dinucleotide context
DINUC_CATEGORY_MAP = {
    "WW-WW":           {"WW-WW"},
    "SS-SS":           {"SS-SS"},
    "SW-WS":           {"SW-WS"},
    "WS-SW":           {"WS-SW"},
    "WW-WS + SW-WW":           {"WW-WS", "SW-WW"},
    "WW-SW + WS-WW":           {"WW-SW", "WS-WW"},
    "WW-SS + SS-WW":           {"WW-SS", "SS-WW"},
    "WS-SS + SS-SW":           {"WS-SS", "SS-SW"},
    "SW-SS + SS-WS":           {"SW-SS", "SS-WS"},
    "WS-WS + SW-SW":           {"WS-WS", "SW-SW"},
}

#helper functions to categorize bases
def base_to_WS(b):
    """Map nucleotide to W/S; return None for N/other.
    b is a string"""
    b = b.upper()
    if b in ("A", "T"):
        return "W"
    elif b in ("C", "G"):
        return "S"
    else:
        return None

def dinuc_from_two(b1, b2):
    """Return 'WW','SS','WS','SW' or None if any base is None.
    both b1 and b2 are strings"""
    if b1 is None or b2 is None:
        return None
    return b1 + b2

def classify_5bp_window(win5):
    """
    Take a 5bp window, look at first two and last two bases,
    return a concrete pattern string like 'WW-SS' or None if ambiguous.

    win5 is a string of length 5
    """
    if len(win5) < 5:
        return None
    w0 = base_to_WS(win5[0])
    w1 = base_to_WS(win5[1])
    w3 = base_to_WS(win5[3])
    w4 = base_to_WS(win5[4])

    left  = dinuc_from_two(w0, w1)
    right = dinuc_from_two(w3, w4)
    if left is None or right is None:
        return None
    return f"{left}-{right}"

def map_pattern_to_category(pattern):
    """Map a concrete pattern (e.g. 'WW-SS') to one of the 8 merged categories.
    """
    for cat, patterns in DINUC_CATEGORY_MAP.items():
        if pattern in patterns:
            return cat
    return None

In [5]:
def classify_nucleosome_sequence(seq150):
    """
    Slide non-overlapping 5bp windows across seq150,
    count matches for each of the 8 merged categories,
    return the category with the highest count.

    seq150 is a string of length 150 (DNA bases)
    """
    if len(seq150) != 150:
        raise ValueError("Expected 150bp sequence")

    # init counts to 0 for each category
    counts = {cat: 0 for cat in DINUC_CATEGORY_MAP.keys()}

    for i in range(0, 150, 5):
        win = seq150[i:i+5]
        if len(win) < 5:
            continue
        pattern = classify_5bp_window(win)
        if pattern is None:
            continue
        cat = map_pattern_to_category(pattern)
        if cat is not None:
            counts[cat] += 1

    # if everything stayed 0:
    if all(v == 0 for v in counts.values()):
        return "UNKNOWN"

    # pick key with max value
    best_cat = max(counts, key=lambda k: counts[k])
    return best_cat

In [6]:
# creating a dictionary with the dinucleotide categories: WW-WW + SS-SS, WW-WS + SS-SW, 
# WW-SW + SS-WS, WW-SS + SS-WW, WS-SS + SW-WW, SW-SS + WS-WW, WS+SW + SW-WS, WS-WS + SW-SW, WS+SW + SW-WS
#then, for each 5bp window, categorize the first two and last two bases, then find which dinucleotide category it falls under + keep an internal count to see which of the 8 dinucleotide categories had the most matches
# assign nucleosome to the dinucleotide category with the most amount of matches -> add this category to a new column in the nuc dataframe

plusone_nuc["dinuc_category"] = plusone_nuc["dyad_sequence"].apply(classify_nucleosome_sequence)
plustwo_nuc["dinuc_category"] = plustwo_nuc["dyad_sequence"].apply(classify_nucleosome_sequence)

In [10]:
plustwo_nuc

,chr,start,end,NAME,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15,col16,col17,phase,dyad_sequence,dinuc_category
0,chr1,2229073,2229073,chr1_2229073_2229073,222,+,0.183908,sameYR_lowWS,chr1,2228033,2228033,chr1_2228033_2228033,999,+,816,-3_CT_-2_-1_CA_0_1_GT_2_c_main_NFR_First_Refer...,1040,0,CGCCTGTGTCTGCCGCAGATTCTCAACTCGGTGCTGCGCGACTTCT...,WS-WS + SW-SW
1,chr1,3857730,3857730,chr1_3857730_3857730,158,+,0.119047,sameYR_lowWS,chr1,3857460,3857460,chr1_3857460_3857460,131,+,110,-3_TG_-2_-1_TA_0_1_GT_2_c_main_NFR_First_Refer...,270,0,GCTTTTCCTCTTCCAAAACGGAGGGTGCAGGCGGCGCCCGGGGCGG...,SS-SS
2,chr1,6393995,6393995,chr1_6393995_6393995,346,+,0.140000,sameYR_lowWS,chr1,6393535,6393535,chr1_6393535_6393535,158,+,112,-3_GC_-2_-1_CA_0_1_AG_2_c_main_NFR_First_Diver...,460,0,AAGCGTCACGAGGTGGGGAGGAGGAAAGGCCGGCGACTATCTACAC...,WS-WS + SW-SW
3,chr1,9234225,9234225,chr1_9234225_9234225,277,-,0.141414,sameYR_lowWS,chr1,9234605,9234605,chr1_9234605_9234605,28,-,101,-3_TC_-2_-1_CC_0_1_TT_2_c_main_NFR_First_Diver...,380,0,GTACAGATGAAGAAACTGAACTCAGGGTCACACAAGTGATAAGGGG...,WW-WS + SW-WW
4,chr1,11011982,11011982,chr1_11011982_11011982,149,-,0.107345,sameYR_lowWS,chr1,11012272,11012272,chr1_11012272_11012272,87,-,139,-3_GG_-2_-1_GA_0_1_TC_2_c_main_NFR_First_Refer...,290,0,CCTCACCCGCAGAATGAATATCAATAGCTCCTGCTACACAAAACTG...,WW-SW + WS-WW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45440,chr9,93096676,93096676,chr9_93096676_93096676,122,+,0.000000,lessDNAencode,chr9,93096217,93096217,chr9_93096217_93096217,110,+,335,-3_AG_-2_-1_CC_0_1_AA_2_c_main_NFR_First_Diver...,459,9,GGTGGTAGAAATGACACCGGAGAGAATTCACAGCGGTCCTGCTGTG...,WS-SS + SS-SW
45441,chr9,129024363,129024363,chr9_129024363_129024363,187,+,0.000000,lessDNAencode,chr9,129023924,129023924,chr9_129023924_129023924,6,+,3,-3_AT_-2_-1_TA_0_1_CC_2_c_main_NDR_First_Singl...,439,9,AGCCGGGTGTGGTGGCGGGCACGTGTAGACCCAGTAACTCGGGAGG...,WS-SS + SS-SW
45442,chrX,103554656,103554656,chrX_103554656_103554656,196,-,0.000000,lessDNAencode,chrX,103554945,103554945,chrX_103554945_103554945,20,-,91,-3_TT_-2_-1_TA_0_1_AT_2_c_main_NFR_First_Singl...,289,9,TTGGAAAGTAGCTCCGGGACACCCCTGGAGCAGGACACCACATTCA...,WS-WS + SW-SW
45443,chrX,119333906,119333906,chrX_119333906_119333906,387,+,0.000000,lessDNAencode,chrX,119332947,119332947,chrX_119332947_119332947,26,+,570,-3_GG_-2_-1_CA_0_1_AC_2_c_main_NFR_First_Singl...,959,9,CCACCCAAGGGCTGAGGAGTGCGGGCGCATGGCGCAGGACTGGCAT...,WS-WS + SW-SW
45444,chrX,154411126,154411126,chrX_154411126_154411126,207,-,0.000000,lessDNAencode,chrX,154411475,154411475,chrX_154411475_154411475,190,-,140,-3_GG_-2_-1_CA_0_1_GC_2_c_main_NFR_First_Refer...,349,9,CTCACGGCTGTCATCCCAACACTTTGGGAGGCCGAGGCGGGTGGAT...,SS-SS

In [11]:
# counts of dinuc_category
plustwo_nuc["dinuc_category"].value_counts()

dinuc_category
WS-SS + SS-SW    8424
SW-SS + SS-WS    7196
SS-SS            6820
WW-WS + SW-WW    6439
WW-SW + WS-WW    4973
WS-WS + SW-SW    4407
WW-WW            3671
WW-SS + SS-WW    1634
SW-WS            1003
WS-SW             878
Name: count, dtype: int64

In [7]:
# exporting
def sanitize_category_name(cat):
    """
    Turn category name into something safe for directory/file names.
    """
    return (
        cat.replace(" ", "_")
           .replace("+", "plus")
           .replace("/", "_")
           .replace("-", "_")
    )

def write_bed(df, path):
    """
    Write a 3-column BED (chrom, start, end) from a dataframe.
    Assumes columns are named 'chrom', 'start', 'end'.
    """
    df.to_csv(path, sep="\t", header=False, index=False)

base_dir = "/home/ubuntu/honors_research/peak_align/reference_files"

def export_by_dinuc_and_phase(df, root_name: str):
    """
    For a given nucleosome dataframe:
      - create root folder: base_dir/root_name  (e.g. '+1_dinucleotide')
      - for each dinuc_category, create a subfolder
      - inside each category folder, write one BED per phase
    Assumes df has columns: 'chrom', 'start', 'end', 'phase', 'dinuc_category'.
    """
    out_root = os.path.join(base_dir, root_name)
    os.makedirs(out_root, exist_ok=True)

    dinuc_categories = df["dinuc_category"].dropna().unique()

    for cat in dinuc_categories:
        cat_df = df[df["dinuc_category"] == cat]
        if cat_df.empty:
            continue

        safe_cat = sanitize_category_name(cat)
        cat_dir = os.path.join(out_root, safe_cat)
        os.makedirs(cat_dir, exist_ok=True)

        # loop over phases present in this category
        for phase in sorted(cat_df["phase"].unique()):
            phase_df = cat_df[cat_df["phase"] == phase]
            if phase_df.empty:
                continue

            bed_name = f"{safe_cat}_phase{phase}.bed"
            bed_path = os.path.join(cat_dir, bed_name)
            write_bed(phase_df, bed_path)

# Export +1 and +2 nucleosomes
export_by_dinuc_and_phase(plusone_nuc, "+1_dinucleotide")
#export_by_dinuc_and_phase(plustwo_nuc, "+2_dinucleotide")

Old Dinucleotide Categories - do not use

In [8]:
def add_context_column(df, reference_genome_path):
    """
    Adds a 'context' column to the DataFrame with the nucleotide context (before, SNP, after).

    Parameters:
    df (pd.DataFrame): DataFrame containing mutation information with 'chrom', 'start', and 'end' columns (0-based).
    reference_genome_path (str): Path to the reference genome (e.g., hg38.fa.gz).

    Returns:
    pd.DataFrame: Updated DataFrame with a new 'context' column.
    """
    # Load the reference genome
    fasta = pysam.FastaFile(reference_genome_path)

    # Function to fetch context for a single mutation
    def fetch_context(row):
        try:
            chrom = row['chr']
            pos = row['start'] +1  # Convert 0-based to 1-based for pysam
            
            before_2 = fasta.fetch(chrom, pos - 3, pos - 2) # Nucleotide before -1
            before = fasta.fetch(chrom, pos - 2, pos - 1)  # Nucleotide before
            ref = fasta.fetch(chrom, pos - 1, pos)  # Reference nucleotide at the SNP position
            after = fasta.fetch(chrom, pos, pos + 1)  # Nucleotide after
            after_2 = fasta.fetch(chrom, pos + 1, pos + 2) # Nucleotide after +1

            # Making everything in caps
            before = before.upper()
            before_2 = before_2.upper()
            ref = ref.upper()
            after = after.upper()
            after_2 = after_2.upper()



            #return f"{before}{ref}{after}"
            return f"{before_2}{before}{ref}{after}{after_2}"
        except KeyError:
            # Handle cases where the chromosome is not found in the reference genome
            return "Context not found"

    # Apply the fetch_context function to each row in the DataFrame
    df['context'] = df.apply(fetch_context, axis=1)

    return df

In [9]:

dinucleotide_plusone = add_context_column(plusone_nuc, "/home/ubuntu/honors_research/hg38.fa")
dinucleotide_plustwo = add_context_column(plustwo_nuc, "/home/ubuntu/honors_research/hg38.fa")

In [10]:
dinucleotide_plusone

,chr,start,end,NAME,col5,col6,col7,col8,phase,context
0,chr1,999644,999644,chr1_999644_999644,450,-,0.051948,YRWS,0,GTCAG
1,chr1,1013609,1013609,chr1_1013609_1013609,140,+,0.202247,YRWS,0,GGCTC
2,chr1,1020730,1020730,chr1_1020730_1020730,610,+,0.253522,lowYR_sameWS,0,GCTTG
3,chr1,1185518,1185518,chr1_1185518_1185518,130,-,0.168142,lessDNAencode,0,TCTCC
4,chr1,1231866,1231866,chr1_1231866_1231866,230,+,0.129033,antiYR_antiWS,0,AGCGG
...,...,...,...,...,...,...,...,...,...,...
45543,chrX,154479147,154479147,chrX_154479147_154479147,79,+,0.130435,YRWS,9,TCTGC
45544,chrX,154547463,154547463,chrX_154547463_154547463,99,-,0.000000,antiYR_antiWS,9,CATTA
45545,chrX,154801954,154801954,chrX_154801954_154801954,119,+,0.142857,YRWS,9,ACCAT
45546,chrX,154805749,154805749,chrX_154805749_154805749,139,+,0.134615,sameYR_lowWS,9,AGCCG
45547,chrX,155881108,155881108,chrX_155881108_155881108,89,-,0.225000,lessDNAencode,9,ATTTT

In [11]:
#dinucleotide recoding
def dinucleotide_recoding(context_column):
            

    before_2 = context_column[0]
    before = context_column[1]
    ref = context_column[2]
    after = context_column[3]
    after_2 = context_column[4]
    
    before = 'W' if before in ['A', 'T'] else 'S'
    before_2 = 'W' if before_2 in ['A', 'T'] else 'S'
    ref = 'W' if ref in ['A', 'T'] else 'S'
    after = 'W' if after in ['A', 'T'] else 'S'
    after_2 = 'N'

    return f"{before_2}{before}{ref}{after}{after_2}"

In [12]:
# Apply the recoding function to the 'context' column, and create a new column for results
dinucleotide_plusone['recoded_context'] = dinucleotide_plusone['context'].apply(dinucleotide_recoding)
dinucleotide_plustwo['recoded_context'] = dinucleotide_plustwo['context'].apply(dinucleotide_recoding)

In [13]:
dinucleotide_plusone

,chr,start,end,NAME,col5,col6,col7,col8,phase,context,recoded_context
0,chr1,999644,999644,chr1_999644_999644,450,-,0.051948,YRWS,0,GTCAG,SWSWN
1,chr1,1013609,1013609,chr1_1013609_1013609,140,+,0.202247,YRWS,0,GGCTC,SSSWN
2,chr1,1020730,1020730,chr1_1020730_1020730,610,+,0.253522,lowYR_sameWS,0,GCTTG,SSWWN
3,chr1,1185518,1185518,chr1_1185518_1185518,130,-,0.168142,lessDNAencode,0,TCTCC,WSWSN
4,chr1,1231866,1231866,chr1_1231866_1231866,230,+,0.129033,antiYR_antiWS,0,AGCGG,WSSSN
...,...,...,...,...,...,...,...,...,...,...,...
45543,chrX,154479147,154479147,chrX_154479147_154479147,79,+,0.130435,YRWS,9,TCTGC,WSWSN
45544,chrX,154547463,154547463,chrX_154547463_154547463,99,-,0.000000,antiYR_antiWS,9,CATTA,SWWWN
45545,chrX,154801954,154801954,chrX_154801954_154801954,119,+,0.142857,YRWS,9,ACCAT,WSSWN
45546,chrX,154805749,154805749,chrX_154805749_154805749,139,+,0.134615,sameYR_lowWS,9,AGCCG,WSSSN
45547,chrX,155881108,155881108,chrX_155881108_155881108,89,-,0.225000,lessDNAencode,9,ATTTT,WWWWN

In [14]:
# table for dinucleotide contexts counts
dinucleotide_plusone['recoded_context'].value_counts().reset_index()
dinucleotide_plustwo['recoded_context'].value_counts().reset_index()

   recoded_context  count
0            SSSSN   4058
1            SSWSN   3924
2            SWSSN   3841
3            WSSSN   3301
4            SSSWN   3293
5            WSWSN   3253
6            SWSWN   3229
7            WSSWN   2695
8            WWWWN   2474
9            SWWSN   2421
10           WWSWN   2342
11           WSWWN   2272
12           SSWWN   2177
13           WWSSN   2100
14           SWWWN   2050
15           WWWSN   2015

In [15]:
#high S = >= 4 S
#medium S = 2-3 S
#low = 1


def categorize_dinucleotide(context):
    s_count = context.count("S")  # how many G/C positions
    if s_count >= 4:
        return "High_S"
    elif 2<= s_count <= 3:
        return "Medium_S"
    elif s_count <= 1:
        return "Low_S"
 

print(dinucleotide_plustwo['context'].head())

0    GACCG
1    GCTAG
2    CGGCT
3    AGCAC
4    TAATC
Name: context, dtype: object

In [18]:
dinucleotide_plusone['category'] = dinucleotide_plusone['recoded_context'].apply(categorize_dinucleotide)
dinucleotide_plustwo['category'] = dinucleotide_plustwo['recoded_context'].apply(categorize_dinucleotide)

In [17]:
dinucleotide_plusone

,chr,start,end,NAME,col5,col6,col7,col8,phase,context,recoded_context,category
0,chr1,999644,999644,chr1_999644_999644,450,-,0.051948,YRWS,0,GTCAG,SWSWN,Medium_S
1,chr1,1013609,1013609,chr1_1013609_1013609,140,+,0.202247,YRWS,0,GGCTC,SSSWN,Medium_S
2,chr1,1020730,1020730,chr1_1020730_1020730,610,+,0.253522,lowYR_sameWS,0,GCTTG,SSWWN,Medium_S
3,chr1,1185518,1185518,chr1_1185518_1185518,130,-,0.168142,lessDNAencode,0,TCTCC,WSWSN,Medium_S
4,chr1,1231866,1231866,chr1_1231866_1231866,230,+,0.129033,antiYR_antiWS,0,AGCGG,WSSSN,Medium_S
...,...,...,...,...,...,...,...,...,...,...,...,...
45543,chrX,154479147,154479147,chrX_154479147_154479147,79,+,0.130435,YRWS,9,TCTGC,WSWSN,Medium_S
45544,chrX,154547463,154547463,chrX_154547463_154547463,99,-,0.000000,antiYR_antiWS,9,CATTA,SWWWN,Low_S
45545,chrX,154801954,154801954,chrX_154801954_154801954,119,+,0.142857,YRWS,9,ACCAT,WSSWN,Medium_S
45546,chrX,154805749,154805749,chrX_154805749_154805749,139,+,0.134615,sameYR_lowWS,9,AGCCG,WSSSN,Medium_S
45547,chrX,155881108,155881108,chrX_155881108_155881108,89,-,0.225000,lessDNAencode,9,ATTTT,WWWWN,Low_S

In [19]:
# separate into separate data frames

#+1
strong_plusone_df = dinucleotide_plusone[dinucleotide_plusone['category'] == 'High_S']
weak_plusone_df = dinucleotide_plusone[dinucleotide_plusone['category'] == 'Low_S']
med_plusone_df = dinucleotide_plusone[dinucleotide_plusone['category'] == 'Medium_S']

#+2
strong_plustwo_df = dinucleotide_plustwo[dinucleotide_plustwo['category'] == 'High_S']
weak_plustwo_df = dinucleotide_plustwo[dinucleotide_plustwo['category'] == 'Low_S']
med_plustwo_df = dinucleotide_plustwo[dinucleotide_plustwo['category'] == 'Medium_S']

In [24]:
# exporting (dropping the category column) + separating by phase

#+1 nucleosomes

#strong
strong_plusone_df[strong_plusone_df['phase'] == 0].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/strong_+1_nuc/strong_+1_phase0.bed", sep='\t', index=False, header=False)
strong_plusone_df[strong_plusone_df['phase'] == 1].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/strong_+1_nuc/strong_+1_phase1.bed", sep='\t', index=False, header=False)
strong_plusone_df[strong_plusone_df['phase'] == 2].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/strong_+1_nuc/strong_+1_phase2.bed", sep='\t', index=False, header=False)
strong_plusone_df[strong_plusone_df['phase'] == 3].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/strong_+1_nuc/strong_+1_phase3.bed", sep='\t', index=False, header=False)
strong_plusone_df[strong_plusone_df['phase'] == 4].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/strong_+1_nuc/strong_+1_phase4.bed", sep='\t', index=False, header=False)
strong_plusone_df[strong_plusone_df['phase'] == 5].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/strong_+1_nuc/strong_+1_phase5.bed", sep='\t', index=False, header=False)
strong_plusone_df[strong_plusone_df['phase'] == 6].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/strong_+1_nuc/strong_+1_phase6.bed", sep='\t', index=False, header=False)
strong_plusone_df[strong_plusone_df['phase'] == 7].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/strong_+1_nuc/strong_+1_phase7.bed", sep='\t', index=False, header=False)
strong_plusone_df[strong_plusone_df['phase'] == 8].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/strong_+1_nuc/strong_+1_phase8.bed", sep='\t', index=False, header=False)
strong_plusone_df[strong_plusone_df['phase'] == 9].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/strong_+1_nuc/strong_+1_phase9.bed", sep='\t', index=False, header=False)

#weak
weak_plusone_df[weak_plusone_df['phase'] == 0].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/weak_+1_nuc/weak_+1_phase0.bed", sep='\t', index=False, header=False)
weak_plusone_df[weak_plusone_df['phase'] == 1].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/weak_+1_nuc/weak_+1_phase1.bed", sep='\t', index=False, header=False)
weak_plusone_df[weak_plusone_df['phase'] == 2].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/weak_+1_nuc/weak_+1_phase2.bed", sep='\t', index=False, header=False)
weak_plusone_df[weak_plusone_df['phase'] == 3].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/weak_+1_nuc/weak_+1_phase3.bed", sep='\t', index=False, header=False)
weak_plusone_df[weak_plusone_df['phase'] == 4].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/weak_+1_nuc/weak_+1_phase4.bed", sep='\t', index=False, header=False)
weak_plusone_df[weak_plusone_df['phase'] == 5].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/weak_+1_nuc/weak_+1_phase5.bed", sep='\t', index=False, header=False)
weak_plusone_df[weak_plusone_df['phase'] == 6].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/weak_+1_nuc/weak_+1_phase6.bed", sep='\t', index=False, header=False)
weak_plusone_df[weak_plusone_df['phase'] == 7].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/weak_+1_nuc/weak_+1_phase7.bed", sep='\t', index=False, header=False)
weak_plusone_df[weak_plusone_df['phase'] == 8].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/weak_+1_nuc/weak_+1_phase8.bed", sep='\t', index=False, header=False)
weak_plusone_df[weak_plusone_df['phase'] == 9].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/weak_+1_nuc/weak_+1_phase9.bed", sep='\t', index=False, header=False)

#medium
med_plusone_df[med_plusone_df['phase'] == 0].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/med_+1_nuc/medium_+1_phase0.bed", sep='\t', index=False, header=False)
med_plusone_df[med_plusone_df['phase'] == 1].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/med_+1_nuc/medium_+1_phase1.bed", sep='\t', index=False, header=False)
med_plusone_df[med_plusone_df['phase'] == 2].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/med_+1_nuc/medium_+1_phase2.bed", sep='\t', index=False, header=False)
med_plusone_df[med_plusone_df['phase'] == 3].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/med_+1_nuc/medium_+1_phase3.bed", sep='\t', index=False, header=False)
med_plusone_df[med_plusone_df['phase'] == 4].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/med_+1_nuc/medium_+1_phase4.bed", sep='\t', index=False, header=False)
med_plusone_df[med_plusone_df['phase'] == 5].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/med_+1_nuc/medium_+1_phase5.bed", sep='\t', index=False, header=False)
med_plusone_df[med_plusone_df['phase'] == 6].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/med_+1_nuc/medium_+1_phase6.bed", sep='\t', index=False, header=False)
med_plusone_df[med_plusone_df['phase'] == 7].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/med_+1_nuc/medium_+1_phase7.bed", sep='\t', index=False, header=False)
med_plusone_df[med_plusone_df['phase'] == 8].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/med_+1_nuc/medium_+1_phase8.bed", sep='\t', index=False, header=False)
med_plusone_df[med_plusone_df['phase'] == 9].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/med_+1_nuc/medium_+1_phase9.bed", sep='\t', index=False, header=False)

#+2
#strong
strong_plustwo_df[strong_plustwo_df['phase'] == 0].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/strong_+2_nuc/strong_+2_phase0.bed", sep='\t', index=False, header=False)
strong_plustwo_df[strong_plustwo_df['phase'] == 1].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/strong_+2_nuc/strong_+2_phase1.bed", sep='\t', index=False, header=False)
strong_plustwo_df[strong_plustwo_df['phase'] == 2].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/strong_+2_nuc/strong_+2_phase2.bed", sep='\t', index=False, header=False)
strong_plustwo_df[strong_plustwo_df['phase'] == 3].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/strong_+2_nuc/strong_+2_phase3.bed", sep='\t', index=False, header=False)
strong_plustwo_df[strong_plustwo_df['phase'] == 4].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/strong_+2_nuc/strong_+2_phase4.bed", sep='\t', index=False, header=False)
strong_plustwo_df[strong_plustwo_df['phase'] == 5].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/strong_+2_nuc/strong_+2_phase5.bed", sep='\t', index=False, header=False)
strong_plustwo_df[strong_plustwo_df['phase'] == 6].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/strong_+2_nuc/strong_+2_phase6.bed", sep='\t', index=False, header=False)
strong_plustwo_df[strong_plustwo_df['phase'] == 7].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/strong_+2_nuc/strong_+2_phase7.bed", sep='\t', index=False, header=False)
strong_plustwo_df[strong_plustwo_df['phase'] == 8].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/strong_+2_nuc/strong_+2_phase8.bed", sep='\t', index=False, header=False)
strong_plustwo_df[strong_plustwo_df['phase'] == 9].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/strong_+2_nuc/strong_+2_phase9.bed", sep='\t', index=False, header=False)

#weak
weak_plustwo_df[weak_plustwo_df['phase'] == 0].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/weak_+2_nuc/weak_+2_phase0.bed", sep='\t', index=False, header=False)
weak_plustwo_df[weak_plustwo_df['phase'] == 1].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/weak_+2_nuc/weak_+2_phase1.bed", sep='\t', index=False, header=False)
weak_plustwo_df[weak_plustwo_df['phase'] == 2].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/weak_+2_nuc/weak_+2_phase2.bed", sep='\t', index=False, header=False)
weak_plustwo_df[weak_plustwo_df['phase'] == 3].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/weak_+2_nuc/weak_+2_phase3.bed", sep='\t', index=False, header=False)
weak_plustwo_df[weak_plustwo_df['phase'] == 4].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/weak_+2_nuc/weak_+2_phase4.bed", sep='\t', index=False, header=False)
weak_plustwo_df[weak_plustwo_df['phase'] == 5].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/weak_+2_nuc/weak_+2_phase5.bed", sep='\t', index=False, header=False)
weak_plustwo_df[weak_plustwo_df['phase'] == 6].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/weak_+2_nuc/weak_+2_phase6.bed", sep='\t', index=False, header=False)
weak_plustwo_df[weak_plustwo_df['phase'] == 7].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/weak_+2_nuc/weak_+2_phase7.bed", sep='\t', index=False, header=False)
weak_plustwo_df[weak_plustwo_df['phase'] == 8].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/weak_+2_nuc/weak_+2_phase8.bed", sep='\t', index=False, header=False)
weak_plustwo_df[weak_plustwo_df['phase'] == 9].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/weak_+2_nuc/weak_+2_phase9.bed", sep='\t', index=False, header=False)

#medium
med_plustwo_df[med_plustwo_df['phase'] == 0].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/med_+2_nuc/medium_+2_phase0.bed", sep='\t', index=False, header=False)
med_plustwo_df[med_plustwo_df['phase'] == 1].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/med_+2_nuc/medium_+2_phase1.bed", sep='\t', index=False, header=False)
med_plustwo_df[med_plustwo_df['phase'] == 2].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/med_+2_nuc/medium_+2_phase2.bed", sep='\t', index=False, header=False)
med_plustwo_df[med_plustwo_df['phase'] == 3].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/med_+2_nuc/medium_+2_phase3.bed", sep='\t', index=False, header=False)
med_plustwo_df[med_plustwo_df['phase'] == 4].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/med_+2_nuc/medium_+2_phase4.bed", sep='\t', index=False, header=False)
med_plustwo_df[med_plustwo_df['phase'] == 5].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/med_+2_nuc/medium_+2_phase5.bed", sep='\t', index=False, header=False)
med_plustwo_df[med_plustwo_df['phase'] == 6].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/med_+2_nuc/medium_+2_phase6.bed", sep='\t', index=False, header=False)
med_plustwo_df[med_plustwo_df['phase'] == 7].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/med_+2_nuc/medium_+2_phase7.bed", sep='\t', index=False, header=False)
med_plustwo_df[med_plustwo_df['phase'] == 8].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/med_+2_nuc/medium_+2_phase8.bed", sep='\t', index=False, header=False)
med_plustwo_df[med_plustwo_df['phase'] == 9].drop(columns=['context', 'category', 'recoded_context']).to_csv("/home/ubuntu/honors_research/peak_align/reference_files/med_+2_nuc/medium_+2_phase9.bed", sep='\t', index=False, header=False)