In [1]:
import pandas as pd

In [24]:
# Goal: Separate peak align output file into different files based on the phasing of the nucleosome

peak_align_path = "/home/ubuntu/honors_research/conservation_analysis/dinucleotide_context/med_dinucleotide_nuc_250bp/CDT/hg38.phyloP30way_med_dinucleotide_nuc_250bp.cdt"
reference_bed = "/home/ubuntu/honors_research/peak_align/dinucleotide_analysis/med/med_dinucleotide_nuc_250bp.bed"

peak_align = pd.read_csv(peak_align_path, sep="\t")
reference = pd.read_csv(reference_bed, sep="\t", header=None)
reference

,0,1,2,3,4,5,6,7
0,chr16,68085593,68085843,chr16_68085718_68085718,16,+,-8,-3_CT_-2_-1_CG_0_1_AC_2_c_main_NDR_First_Diver...
1,chr1,156747240,156747490,chr1_156747365_156747365,7,+,43,-3_AC_-2_-1_CA_0_1_CA_2_c_main_NFR_First_Diver...
2,chr1,172449864,172450114,chr1_172449989_172449989,10,-,40,-3_TC_-2_-1_CA_0_1_CT_2_c_main_NFR_First_Refer...
3,chr1,223844989,223845239,chr1_223845114_223845114,5,-,41,-3_TG_-2_-1_CA_0_1_GG_2_c_main_NFR_First_Diver...
4,chr1,244048575,244048825,chr1_244048700_244048700,52,+,40,-3_GC_-2_-1_TG_0_1_TG_2_c_main_NFR_First_Diver...
...,...,...,...,...,...,...,...,...
36323,chr18,57435283,57435533,chr18_57435408_57435408,126,+,967,-3_AA_-2_-1_CA_0_1_GA_2_c_main_NFR_First_Refer...
36324,chr19,37251752,37252002,chr19_37251877_37251877,5,+,988,-3_CC_-2_-1_CA_0_1_CG_2_c_main_NFR_First_Singl...
36325,chr8,1701303,1701553,chr8_1701428_1701428,7,-,1000,-3_CG_-2_-1_AG_0_1_GG_2_c_main_NFR_First_Diver...
36326,chr13,108215410,108215660,chr13_108215535_108215535,9,-,21,-3_GG_-2_-1_CA_0_1_TC_2_c_main_NDR_First_Diver...
36327,chr16,1152981,1153231,chr16_1153106_1153106,39,+,1160,-3_CT_-2_-1_CA_0_1_GC_2_c_main_NFR_First_Refer...

In [25]:
#Nuc2 to Nuc4 -> have to manually create phase column (split reference[5] by '_' and take last element)

reference.columns = ["chrom", "start", "end", "name", "number", "score", "numb2", "strand"]
#reference.columns = ["chrom", "start", "end", "name", "score", "strand"]


phase = reference["strand"].str.split("_").str[-1]

#adding phase to the end of reference
reference["phase"] = phase

In [26]:
reference

,chrom,start,end,name,number,score,numb2,strand,phase
0,chr16,68085593,68085843,chr16_68085718_68085718,16,+,-8,-3_CT_-2_-1_CG_0_1_AC_2_c_main_NDR_First_Diver...,phase0
1,chr1,156747240,156747490,chr1_156747365_156747365,7,+,43,-3_AC_-2_-1_CA_0_1_CA_2_c_main_NFR_First_Diver...,phase0
2,chr1,172449864,172450114,chr1_172449989_172449989,10,-,40,-3_TC_-2_-1_CA_0_1_CT_2_c_main_NFR_First_Refer...,phase0
3,chr1,223844989,223845239,chr1_223845114_223845114,5,-,41,-3_TG_-2_-1_CA_0_1_GG_2_c_main_NFR_First_Diver...,phase0
4,chr1,244048575,244048825,chr1_244048700_244048700,52,+,40,-3_GC_-2_-1_TG_0_1_TG_2_c_main_NFR_First_Diver...,phase0
...,...,...,...,...,...,...,...,...,...
36323,chr18,57435283,57435533,chr18_57435408_57435408,126,+,967,-3_AA_-2_-1_CA_0_1_GA_2_c_main_NFR_First_Refer...,phaseno10x
36324,chr19,37251752,37252002,chr19_37251877_37251877,5,+,988,-3_CC_-2_-1_CA_0_1_CG_2_c_main_NFR_First_Singl...,phaseno10x
36325,chr8,1701303,1701553,chr8_1701428_1701428,7,-,1000,-3_CG_-2_-1_AG_0_1_GG_2_c_main_NFR_First_Diver...,phaseno10x
36326,chr13,108215410,108215660,chr13_108215535_108215535,9,-,21,-3_GG_-2_-1_CA_0_1_TC_2_c_main_NDR_First_Diver...,phaseno10x
36327,chr16,1152981,1153231,chr16_1153106_1153106,39,+,1160,-3_CT_-2_-1_CA_0_1_GC_2_c_main_NFR_First_Refer...,phaseno10x

In [27]:

#reference.columns = ["chrom", "start", "end", "name", "score", "strand", "distance_to_nuc", "phase"]
peak_align = peak_align.drop(columns = "YORF")
peak_align

,NAME,0,1,2,3,4,5,6,7,8,...,240,241,242,243,244,245,246,247,248,249
0,chr16_68085718_68085718,1.172,1.020,1.052,1.172,1.172,1.052,0.920,1.052,1.052,...,0.954,-0.560,-0.829,0.111,1.217,0.412,-0.475,0.147,-0.296,1.066
1,chr1_156747365_156747365,1.019,-0.760,-1.186,0.494,0.494,-2.967,-0.008,0.143,0.143,...,1.026,-0.759,-0.247,1.176,0.200,0.170,0.232,0.800,0.800,1.016
2,chr1_172449989_172449989,0.256,1.000,1.146,1.278,1.146,-0.062,0.289,-0.994,-1.029,...,0.085,-0.986,-0.590,0.065,-0.117,-0.254,-1.443,0.186,-0.258,0.184
3,chr1_223845114_223845114,0.893,-0.094,-0.017,-1.309,-0.057,0.122,-0.030,-0.508,0.915,...,-0.243,0.926,-0.386,0.167,0.063,0.922,-0.451,-0.718,-1.171,0.926
4,chr1_244048700_244048700,0.828,0.805,0.828,0.729,0.828,0.805,0.828,0.729,0.828,...,-0.143,0.666,0.590,0.561,0.576,0.666,0.666,0.666,-0.244,0.666
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36323,chr18_57435408_57435408,-0.300,-2.114,-1.454,0.076,-0.970,-0.665,0.054,0.951,-0.783,...,-0.165,0.640,0.640,-0.133,0.724,0.706,0.640,0.640,0.724,0.640
36324,chr19_37251877_37251877,0.263,0.263,0.322,-0.689,0.285,0.296,0.296,-0.756,0.285,...,0.149,0.149,0.161,0.167,0.149,0.149,0.161,0.181,0.181,0.149
36325,chr8_1701428_1701428,-0.048,-0.089,0.790,-0.548,0.101,-0.123,1.071,0.152,0.138,...,-2.521,0.980,1.121,1.121,1.086,0.227,0.071,1.086,0.980,-0.159
36326,chr13_108215535_108215535,-1.399,-3.927,-1.537,-0.611,-0.042,-0.680,-0.106,-0.559,-2.076,...,-0.411,-0.427,-0.543,-0.830,-0.303,-0.353,0.504,-1.082,-2.893,0.380
36327,chr16_1153106_1153106,-0.154,-0.854,-0.117,-0.258,0.687,-0.292,-0.938,0.704,0.704,...,-0.285,0.567,0.507,0.567,0.567,-0.283,-0.274,0.558,-0.274,-0.902

In [30]:
#peak_align.to_csv("/home/ubuntu/honors_research/peak_align/hg19/K562_PlusOneDyad_SORT-Expression_WithUnexpressed_500bp_Output_edited.cdt", )

In [28]:
#keep name and phase columns
reference_updated = reference[["name", "phase"]]

In [29]:

for i in range(len(reference_updated["phase"])):
    phase_name = reference_updated["phase"][i]
    phase_i = phase_name.find("phase")
    phase = phase_name[phase_i:]
    #print(phase)

    reference_updated.loc[i, "phase"] = phase

In [30]:
reference_updated

                            name       phase
0        chr16_68085718_68085718      phase0
1       chr1_156747365_156747365      phase0
2       chr1_172449989_172449989      phase0
3       chr1_223845114_223845114      phase0
4       chr1_244048700_244048700      phase0
...                          ...         ...
36323    chr18_57435408_57435408  phaseno10x
36324    chr19_37251877_37251877  phaseno10x
36325       chr8_1701428_1701428  phaseno10x
36326  chr13_108215535_108215535  phaseno10x
36327      chr16_1153106_1153106  phaseno10x

[36328 rows x 2 columns]

In [31]:
# separating the peak align file into different files based on the phasing of the nucleosome, using reference as the mapping
 
peak_align["phase"] = reference["phase"]
peak_align

#might need to add reference_updated name as separate column in peak_align

,NAME,0,1,2,3,4,5,6,7,8,...,241,242,243,244,245,246,247,248,249,phase
0,chr16_68085718_68085718,1.172,1.020,1.052,1.172,1.172,1.052,0.920,1.052,1.052,...,-0.560,-0.829,0.111,1.217,0.412,-0.475,0.147,-0.296,1.066,phase0
1,chr1_156747365_156747365,1.019,-0.760,-1.186,0.494,0.494,-2.967,-0.008,0.143,0.143,...,-0.759,-0.247,1.176,0.200,0.170,0.232,0.800,0.800,1.016,phase0
2,chr1_172449989_172449989,0.256,1.000,1.146,1.278,1.146,-0.062,0.289,-0.994,-1.029,...,-0.986,-0.590,0.065,-0.117,-0.254,-1.443,0.186,-0.258,0.184,phase0
3,chr1_223845114_223845114,0.893,-0.094,-0.017,-1.309,-0.057,0.122,-0.030,-0.508,0.915,...,0.926,-0.386,0.167,0.063,0.922,-0.451,-0.718,-1.171,0.926,phase0
4,chr1_244048700_244048700,0.828,0.805,0.828,0.729,0.828,0.805,0.828,0.729,0.828,...,0.666,0.590,0.561,0.576,0.666,0.666,0.666,-0.244,0.666,phase0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36323,chr18_57435408_57435408,-0.300,-2.114,-1.454,0.076,-0.970,-0.665,0.054,0.951,-0.783,...,0.640,0.640,-0.133,0.724,0.706,0.640,0.640,0.724,0.640,phaseno10x
36324,chr19_37251877_37251877,0.263,0.263,0.322,-0.689,0.285,0.296,0.296,-0.756,0.285,...,0.149,0.161,0.167,0.149,0.149,0.161,0.181,0.181,0.149,phaseno10x
36325,chr8_1701428_1701428,-0.048,-0.089,0.790,-0.548,0.101,-0.123,1.071,0.152,0.138,...,0.980,1.121,1.121,1.086,0.227,0.071,1.086,0.980,-0.159,phaseno10x
36326,chr13_108215535_108215535,-1.399,-3.927,-1.537,-0.611,-0.042,-0.680,-0.106,-0.559,-2.076,...,-0.427,-0.543,-0.830,-0.303,-0.353,0.504,-1.082,-2.893,0.380,phaseno10x
36327,chr16_1153106_1153106,-0.154,-0.854,-0.117,-0.258,0.687,-0.292,-0.938,0.704,0.704,...,0.567,0.507,0.567,0.567,-0.283,-0.274,0.558,-0.274,-0.902,phaseno10x

In [32]:
# Assuming 'peak_align' is your DataFrame and 'phase' is the column to group by
dataframes = {}

for phase_value, group in peak_align.groupby('phase'):
    dataframes[f"{phase_value}"] = group

phase0 = dataframes["phase0"].drop(columns = "phase")
phase1 = dataframes["phase1"].drop(columns = "phase")
phase2 = dataframes["phase2"].drop(columns = "phase")
phase3 = dataframes["phase3"].drop(columns = "phase")
phase4 = dataframes["phase4"].drop(columns = "phase")
phase5 = dataframes["phase5"].drop(columns = "phase")
phase6 = dataframes["phase6"].drop(columns = "phase")
phase7 = dataframes["phase7"].drop(columns = "phase")
phase8 = dataframes["phase8"].drop(columns = "phase")
phase9 = dataframes["phase9"].drop(columns = "phase")
phase10 = dataframes["phaseno10x"].drop(columns = "phase")

In [33]:
#Checking
sum = len(phase0) + len(phase1) + len(phase2) + len(phase3) + len(phase4) + len(phase5) + len(phase6) + len(phase7) + len(phase8) + len(phase9) + len(phase10)
print("Sum: " + str(sum))
print("Total original length: " + str(len(peak_align)))

Sum: 36328
Total original length: 36328

In [34]:
#Exporting

phase0.to_csv("/home/ubuntu/honors_research/conservation_analysis/dinucleotide_context/med_dinucleotide_nuc_250bp/CDT/phase0_conservation_med_250bp.cdt", sep="\t",index=False)
phase1.to_csv("/home/ubuntu/honors_research/conservation_analysis/dinucleotide_context/med_dinucleotide_nuc_250bp/CDT/phase1_conservation_med_250bp.cdt", sep="\t",index=False)
phase2.to_csv("/home/ubuntu/honors_research/conservation_analysis/dinucleotide_context/med_dinucleotide_nuc_250bp/CDT/phase2_conservation_med_250bp.cdt", sep="\t",index=False)
phase3.to_csv("/home/ubuntu/honors_research/conservation_analysis/dinucleotide_context/med_dinucleotide_nuc_250bp/CDT/phase3_conservation_med_250bp.cdt", sep="\t",index=False)
phase4.to_csv("/home/ubuntu/honors_research/conservation_analysis/dinucleotide_context/med_dinucleotide_nuc_250bp/CDT/phase4_conservation_med_250bp.cdt", sep="\t",index=False)
phase5.to_csv("/home/ubuntu/honors_research/conservation_analysis/dinucleotide_context/med_dinucleotide_nuc_250bp/CDT/phase5_conservation_med_250bp.cdt", sep="\t",index=False)
phase6.to_csv("/home/ubuntu/honors_research/conservation_analysis/dinucleotide_context/med_dinucleotide_nuc_250bp/CDT/phase6_conservation_med_250bp.cdt", sep="\t",index=False)
phase7.to_csv("/home/ubuntu/honors_research/conservation_analysis/dinucleotide_context/med_dinucleotide_nuc_250bp/CDT/phase7_conservation_med_250bp.cdt", sep="\t",index=False)
phase8.to_csv("/home/ubuntu/honors_research/conservation_analysis/dinucleotide_context/med_dinucleotide_nuc_250bp/CDT/phase8_conservation_med_250bp.cdt", sep="\t",index=False)
phase9.to_csv("/home/ubuntu/honors_research/conservation_analysis/dinucleotide_context/med_dinucleotide_nuc_250bp/CDT/phase9_conservation_med_250bp.cdt", sep="\t",index=False)
phase10.to_csv("/home/ubuntu/honors_research/conservation_analysis/dinucleotide_context/med_dinucleotide_nuc_250bp/CDT/phase10_conservation_med_250bp.cdt", sep="\t",index=False)