In [27]:
import pandas as pd

In [28]:
# Goal: Separate peak align output file into different files based on the phasing of the nucleosome

peak_align_path = "/home/ubuntu/honors_research/conservation_analysis/edited_TSS_all_adj+1Nuc_4_250bp/CDT/hg38.phyloP30way_edited_TSS_all_adj+1Nuc_4_250bp.cdt"
reference_bed = "/home/ubuntu/honors_research/peak_align/reference_files/edited_TSS_all_adj+1Nuc_4_250bp.bed"

peak_align = pd.read_csv(peak_align_path, sep="\t")
reference = pd.read_csv(reference_bed, sep="\t", header=None)
reference

,0,1,2,3,4,5,6,7
0,chr1,21782324,21782574,chr1_21782449_21782449,5,+,-19,-3_AA_-2_-1_TA_0_1_CT_2_c_main_NDR_First_Diver...
1,chr16,68085623,68085873,chr16_68085748_68085748,16,+,-8,-3_CT_-2_-1_CG_0_1_AC_2_c_main_NDR_First_Diver...
2,chr1,148634164,148634414,chr1_148634289_148634289,5,-,40,-3_AT_-2_-1_TA_0_1_CT_2_c_main_NFR_First_Singl...
3,chr1,156747280,156747530,chr1_156747405_156747405,7,+,43,-3_AC_-2_-1_CA_0_1_CA_2_c_main_NFR_First_Diver...
4,chr1,172449824,172450074,chr1_172449949_172449949,10,-,40,-3_TC_-2_-1_CA_0_1_CT_2_c_main_NFR_First_Refer...
...,...,...,...,...,...,...,...,...
51311,chr18,57436251,57436501,chr18_57436376_57436376,126,+,967,-3_AA_-2_-1_CA_0_1_GA_2_c_main_NFR_First_Refer...
51312,chr19,37252741,37252991,chr19_37252866_37252866,5,+,988,-3_CC_-2_-1_CA_0_1_CG_2_c_main_NFR_First_Singl...
51313,chr8,1700302,1700552,chr8_1700427_1700427,7,-,1000,-3_CG_-2_-1_AG_0_1_GG_2_c_main_NFR_First_Diver...
51314,chr13,108214392,108214642,chr13_108214517_108214517,9,-,21,-3_GG_-2_-1_CA_0_1_TC_2_c_main_NDR_First_Diver...
51315,chr16,1154142,1154392,chr16_1154267_1154267,39,+,1160,-3_CT_-2_-1_CA_0_1_GC_2_c_main_NFR_First_Refer...

In [29]:
#Nuc2 to Nuc4 -> have to manually create phase column (split reference[5] by '_' and take last element)

reference.columns = ["chrom", "start", "end", "name", "number", "score", "numb2", "strand"]
#reference.columns = ["chrom", "start", "end", "name", "score", "strand"]


phase = reference["strand"].str.split("_").str[-1]

#adding phase to the end of reference
reference["phase"] = phase

In [30]:

#reference.columns = ["chrom", "start", "end", "name", "score", "strand", "distance_to_nuc", "phase"]
peak_align = peak_align.drop(columns = "YORF")
peak_align

,NAME,0,1,2,3,4,5,6,7,8,...,240,241,242,243,244,245,246,247,248,249
0,chr1_21782449_21782449,-0.176,-0.044,0.195,-0.684,1.307,1.307,-2.433,0.115,1.113,...,0.245,1.026,0.877,0.970,0.085,0.138,1.312,1.138,0.125,0.199
1,chr16_68085748_68085748,-0.153,-0.216,0.570,-0.534,0.548,0.485,-0.352,0.548,0.485,...,-0.211,0.902,0.047,0.870,0.008,-0.436,0.788,-0.023,-0.502,0.043
2,chr1_148634289_148634289,1.017,1.050,0.140,1.169,1.169,0.881,0.980,0.089,0.018,...,-0.573,-0.665,1.017,1.017,0.918,1.017,0.118,1.169,0.054,-1.222
3,chr1_156747405_156747405,1.006,-0.232,-0.353,1.152,1.286,1.116,0.189,1.152,0.208,...,-0.157,0.245,1.158,1.011,1.097,-0.414,1.292,1.292,1.292,1.292
4,chr1_172449949_172449949,-0.262,-0.780,0.206,1.121,0.166,-1.313,-0.250,1.086,1.086,...,1.312,1.176,-0.040,-1.238,-0.146,0.970,0.039,1.006,0.093,-1.548
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51311,chr18_57436376_57436376,1.089,0.857,0.857,1.089,0.019,0.857,1.089,-0.417,0.857,...,1.164,0.120,1.016,1.016,1.016,1.298,1.298,0.131,1.127,1.127
51312,chr19_37252866_37252866,-1.164,0.181,0.167,0.149,0.181,0.167,0.161,0.181,-1.220,...,0.232,-0.951,0.232,0.232,-0.813,0.214,0.214,0.261,0.240,-0.946
51313,chr8_1700427_1700427,-0.337,-0.223,-0.451,0.062,-1.862,-0.759,0.182,1.113,0.182,...,-1.652,-1.592,-0.244,-0.333,0.594,0.577,-0.815,-0.110,0.703,0.638
51314,chr13_108214517_108214517,-0.142,-0.744,-0.038,-0.218,-0.595,-0.012,0.639,0.605,0.689,...,0.782,-0.075,0.709,-0.204,-0.056,0.782,0.896,-1.085,-0.030,0.809
51315,chr16_1154267_1154267,0.859,-0.545,0.022,-0.521,-0.058,-0.528,0.668,0.576,-0.337,...,-0.477,-2.919,-0.460,-0.460,0.010,-1.982,0.037,-0.618,-0.444,-0.838

In [31]:
#peak_align.to_csv("/home/ubuntu/honors_research/peak_align/hg19/K562_PlusOneDyad_SORT-Expression_WithUnexpressed_500bp_Output_edited.cdt", )

In [32]:
#keep name and phase columns
reference_updated = reference[["name", "phase"]]

In [33]:

for i in range(len(reference_updated["phase"])):
    phase_name = reference_updated["phase"][i]
    phase_i = phase_name.find("phase")
    phase = phase_name[phase_i:]
    #print(phase)

    reference_updated.loc[i, "phase"] = phase

In [34]:
reference_updated

                            name       phase
0         chr1_21782449_21782449      phase0
1        chr16_68085748_68085748      phase0
2       chr1_148634289_148634289      phase0
3       chr1_156747405_156747405      phase0
4       chr1_172449949_172449949      phase0
...                          ...         ...
51311    chr18_57436376_57436376  phaseno10x
51312    chr19_37252866_37252866  phaseno10x
51313       chr8_1700427_1700427  phaseno10x
51314  chr13_108214517_108214517  phaseno10x
51315      chr16_1154267_1154267  phaseno10x

[51316 rows x 2 columns]

In [35]:
# separating the peak align file into different files based on the phasing of the nucleosome, using reference as the mapping
 
peak_align["phase"] = reference["phase"]
peak_align

#might need to add reference_updated name as separate column in peak_align

,NAME,0,1,2,3,4,5,6,7,8,...,241,242,243,244,245,246,247,248,249,phase
0,chr1_21782449_21782449,-0.176,-0.044,0.195,-0.684,1.307,1.307,-2.433,0.115,1.113,...,1.026,0.877,0.970,0.085,0.138,1.312,1.138,0.125,0.199,phase0
1,chr16_68085748_68085748,-0.153,-0.216,0.570,-0.534,0.548,0.485,-0.352,0.548,0.485,...,0.902,0.047,0.870,0.008,-0.436,0.788,-0.023,-0.502,0.043,phase0
2,chr1_148634289_148634289,1.017,1.050,0.140,1.169,1.169,0.881,0.980,0.089,0.018,...,-0.665,1.017,1.017,0.918,1.017,0.118,1.169,0.054,-1.222,phase0
3,chr1_156747405_156747405,1.006,-0.232,-0.353,1.152,1.286,1.116,0.189,1.152,0.208,...,0.245,1.158,1.011,1.097,-0.414,1.292,1.292,1.292,1.292,phase0
4,chr1_172449949_172449949,-0.262,-0.780,0.206,1.121,0.166,-1.313,-0.250,1.086,1.086,...,1.176,-0.040,-1.238,-0.146,0.970,0.039,1.006,0.093,-1.548,phase0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51311,chr18_57436376_57436376,1.089,0.857,0.857,1.089,0.019,0.857,1.089,-0.417,0.857,...,0.120,1.016,1.016,1.016,1.298,1.298,0.131,1.127,1.127,phaseno10x
51312,chr19_37252866_37252866,-1.164,0.181,0.167,0.149,0.181,0.167,0.161,0.181,-1.220,...,-0.951,0.232,0.232,-0.813,0.214,0.214,0.261,0.240,-0.946,phaseno10x
51313,chr8_1700427_1700427,-0.337,-0.223,-0.451,0.062,-1.862,-0.759,0.182,1.113,0.182,...,-1.592,-0.244,-0.333,0.594,0.577,-0.815,-0.110,0.703,0.638,phaseno10x
51314,chr13_108214517_108214517,-0.142,-0.744,-0.038,-0.218,-0.595,-0.012,0.639,0.605,0.689,...,-0.075,0.709,-0.204,-0.056,0.782,0.896,-1.085,-0.030,0.809,phaseno10x
51315,chr16_1154267_1154267,0.859,-0.545,0.022,-0.521,-0.058,-0.528,0.668,0.576,-0.337,...,-2.919,-0.460,-0.460,0.010,-1.982,0.037,-0.618,-0.444,-0.838,phaseno10x

In [36]:
# Assuming 'peak_align' is your DataFrame and 'phase' is the column to group by
dataframes = {}

for phase_value, group in peak_align.groupby('phase'):
    dataframes[f"{phase_value}"] = group

phase0 = dataframes["phase0"].drop(columns = "phase")
phase1 = dataframes["phase1"].drop(columns = "phase")
phase2 = dataframes["phase2"].drop(columns = "phase")
phase3 = dataframes["phase3"].drop(columns = "phase")
phase4 = dataframes["phase4"].drop(columns = "phase")
phase5 = dataframes["phase5"].drop(columns = "phase")
phase6 = dataframes["phase6"].drop(columns = "phase")
phase7 = dataframes["phase7"].drop(columns = "phase")
phase8 = dataframes["phase8"].drop(columns = "phase")
phase9 = dataframes["phase9"].drop(columns = "phase")
phase10 = dataframes["phaseno10x"].drop(columns = "phase")

In [37]:
#Checking
sum = len(phase0) + len(phase1) + len(phase2) + len(phase3) + len(phase4) + len(phase5) + len(phase6) + len(phase7) + len(phase8) + len(phase9) + len(phase10)
print("Sum: " + str(sum))
print("Total original length: " + str(len(peak_align)))

Sum: 51316
Total original length: 51316

In [38]:
#Exporting

phase0.to_csv("/home/ubuntu/honors_research/conservation_analysis/edited_TSS_all_adj+1Nuc_4_250bp/CDT/phase0_conservation4_250bp.cdt", sep="\t",index=False)
phase1.to_csv("/home/ubuntu/honors_research/conservation_analysis/edited_TSS_all_adj+1Nuc_4_250bp/CDT/phase1_conservation4_250bp.cdt", sep="\t",index=False)
phase2.to_csv("/home/ubuntu/honors_research/conservation_analysis/edited_TSS_all_adj+1Nuc_4_250bp/CDT/phase2_conservation4_250bp.cdt", sep="\t",index=False)
phase3.to_csv("/home/ubuntu/honors_research/conservation_analysis/edited_TSS_all_adj+1Nuc_4_250bp/CDT/phase3_conservation4_250bp.cdt", sep="\t",index=False)
phase4.to_csv("/home/ubuntu/honors_research/conservation_analysis/edited_TSS_all_adj+1Nuc_4_250bp/CDT/phase4_conservation4_250bp.cdt", sep="\t",index=False)
phase5.to_csv("/home/ubuntu/honors_research/conservation_analysis/edited_TSS_all_adj+1Nuc_4_250bp/CDT/phase5_conservation4_250bp.cdt", sep="\t",index=False)
phase6.to_csv("/home/ubuntu/honors_research/conservation_analysis/edited_TSS_all_adj+1Nuc_4_250bp/CDT/phase6_conservation4_250bp.cdt", sep="\t",index=False)
phase7.to_csv("/home/ubuntu/honors_research/conservation_analysis/edited_TSS_all_adj+1Nuc_4_250bp/CDT/phase7_conservation4_250bp.cdt", sep="\t",index=False)
phase8.to_csv("/home/ubuntu/honors_research/conservation_analysis/edited_TSS_all_adj+1Nuc_4_250bp/CDT/phase8_conservation4_250bp.cdt", sep="\t",index=False)
phase9.to_csv("/home/ubuntu/honors_research/conservation_analysis/edited_TSS_all_adj+1Nuc_4_250bp/CDT/phase9_conservation4_250bp.cdt", sep="\t",index=False)
phase10.to_csv("/home/ubuntu/honors_research/conservation_analysis/edited_TSS_all_adj+1Nuc_4_250bp/CDT/phase10_conservation4_250bp.cdt", sep="\t",index=False)