This file goes through editing + phasing +2 nucleosomes, as well as exporting +1 nucleosomes for bed expansion + peak align

In [1]:
import pandas as pd

In [2]:
df_plustwo = pd.read_csv("/home/ubuntu/honors_research/peak_align/reference_files/raw_reference/+2_Nuc_all.bed", sep = "\t", header = None)
df_tss_plusone = pd.read_csv("/home/ubuntu/honors_research/peak_align/reference_files/raw_reference/Adj+1Nuc_TSS_core.bed", sep = "\t")

In [ ]:
df_tss_plusone

,plus nucleosome,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,TSS,Unnamed: 9,...,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,core-promoter,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,chr1,827380,827380,chr1_827380_827380,125,-,0.186992,antiYR_sameWS,chr1,827505,...,245,-,126,-3_AT_-2_-1_TA_0_1_TC_2_c_main_NFR_First_Refer...,chr1,827532,827532,chr1_827532_827532,-65.59,-
1,chr1,827763,827763,chr1_827763_827763,63,+,0.148148,lessDNAencode,chr1,827700,...,53,+,66,-3_CG_-2_-1_CG_0_1_TG_2_c_main_NFR_First_Diver...,chr1,827673,827673,chr1_827673_827673,-24.70,+
2,chr1,904146,904146,chr1_904146_904146,291,-,0.125000,sameYR_lowWS,chr1,904437,...,3,-,292,-3_AG_-2_-1_CA_0_1_GA_2_c_main_NFR_First_Diver...,chr1,904464,904464,chr1_904464_904464,-20.20,-
3,chr1,904600,904600,chr1_904600_904600,138,+,0.098684,lessDNAencode,chr1,904462,...,178,+,132,-3_GC_-2_-1_CA_0_1_GG_2_c_main_NFR_First_Refer...,chr1,904435,904435,chr1_904435_904435,-24.06,+
4,chr1,925528,925528,chr1_925528_925528,75,-,0.096774,lowYR_sameWS,chr1,925603,...,9,-,74,-3_GC_-2_-1_TG_0_1_AG_2_c_main_NFR_First_Singl...,chr1,925630,925630,chr1_925630_925630,-40.46,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45543,chrX,155613122,155613122,chrX_155613122_155613122,142,+,0.000000,sameYR_antiWS,chrX,155612980,...,11,+,141,-3_GC_-2_-1_CG_0_1_TG_2_c_main_NFR_Second_Dive...,chrX,155612953,155612953,chrX_155612953_155612953,-32.91,+
45544,chrX,155881108,155881108,chrX_155881108_155881108,89,-,0.225000,lessDNAencode,chrX,155881197,...,39,-,91,-3_AG_-2_-1_TA_0_1_GT_2_c_main_NFR_First_Diver...,chrX,155881224,155881224,chrX_155881224_155881224,-22.74,-
45545,chrX,155881459,155881459,chrX_155881459_155881459,114,+,0.055556,sameYR_lowWS,chrX,155881345,...,145,+,116,-3_AG_-2_-1_CG_0_1_GC_2_c_main_NFR_First_Refer...,chrX,155881318,155881318,chrX_155881318_155881318,-45.14,+
45546,chrX,155881688,155881688,chrX_155881688_155881688,101,+,0.000000,YRWS,chrX,155881587,...,3,+,100,-3_TC_-2_-1_CA_0_1_GT_2_c_main_NFR_First_Diver...,chrX,155881560,155881560,chrX_155881560_155881560,-31.03,+
45547,chrX,155959003,155959003,chrX_155959003_155959003,117,-,0.277778,lessDNAencode,chrX,155959120,...,5,-,117,-3_GT_-2_-1_TA_0_1_AA_2_c_main_NFR_First_Singl...,chrX,155959147,155959147,chrX_155959147_155959147,0.00,-

In [3]:
#keep first 16 columns of df_tss_plusone 
df_tss_plusone_subset = df_tss_plusone.iloc[:, [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]]
df_tss_plusone_subset

,plus nucleosome,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,TSS,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,chr1,827380,827380,chr1_827380_827380,125,-,0.186992,antiYR_sameWS,chr1,827505,827505,chr1_827505_827505,245,-,126,-3_AT_-2_-1_TA_0_1_TC_2_c_main_NFR_First_Refer...
1,chr1,827763,827763,chr1_827763_827763,63,+,0.148148,lessDNAencode,chr1,827700,827700,chr1_827700_827700,53,+,66,-3_CG_-2_-1_CG_0_1_TG_2_c_main_NFR_First_Diver...
2,chr1,904146,904146,chr1_904146_904146,291,-,0.125000,sameYR_lowWS,chr1,904437,904437,chr1_904437_904437,3,-,292,-3_AG_-2_-1_CA_0_1_GA_2_c_main_NFR_First_Diver...
3,chr1,904600,904600,chr1_904600_904600,138,+,0.098684,lessDNAencode,chr1,904462,904462,chr1_904462_904462,178,+,132,-3_GC_-2_-1_CA_0_1_GG_2_c_main_NFR_First_Refer...
4,chr1,925528,925528,chr1_925528_925528,75,-,0.096774,lowYR_sameWS,chr1,925603,925603,chr1_925603_925603,9,-,74,-3_GC_-2_-1_TG_0_1_AG_2_c_main_NFR_First_Singl...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45543,chrX,155613122,155613122,chrX_155613122_155613122,142,+,0.000000,sameYR_antiWS,chrX,155612980,155612980,chrX_155612980_155612980,11,+,141,-3_GC_-2_-1_CG_0_1_TG_2_c_main_NFR_Second_Dive...
45544,chrX,155881108,155881108,chrX_155881108_155881108,89,-,0.225000,lessDNAencode,chrX,155881197,155881197,chrX_155881197_155881197,39,-,91,-3_AG_-2_-1_TA_0_1_GT_2_c_main_NFR_First_Diver...
45545,chrX,155881459,155881459,chrX_155881459_155881459,114,+,0.055556,sameYR_lowWS,chrX,155881345,155881345,chrX_155881345_155881345,145,+,116,-3_AG_-2_-1_CG_0_1_GC_2_c_main_NFR_First_Refer...
45546,chrX,155881688,155881688,chrX_155881688_155881688,101,+,0.000000,YRWS,chrX,155881587,155881587,chrX_155881587_155881587,3,+,100,-3_TC_-2_-1_CA_0_1_GT_2_c_main_NFR_First_Diver...
45547,chrX,155959003,155959003,chrX_155959003_155959003,117,-,0.277778,lessDNAencode,chrX,155959120,155959120,chrX_155959120_155959120,5,-,117,-3_GT_-2_-1_TA_0_1_AA_2_c_main_NFR_First_Singl...

In [6]:
colnames = ['chr_plusone', 'start_plusone_adj', 'end_plusone_adj', 'id_plusone_adj', 'distance_plusone_adj', 'strand_plusone_adj', 'score_plusone_adj', 'context_plusone_adj', 'chr_tss', 'start_tss', 'end_tss', 'id_tss', 'distance_tss', 'strand_tss', 'score_tss', 'context_tss']
df_tss_plusone_subset.columns = colnames
df_tss_plusone_subset

,chr_plusone,start_plusone_adj,end_plusone_adj,id_plusone_adj,distance_plusone_adj,strand_plusone_adj,score_plusone_adj,context_plusone_adj,chr_tss,start_tss,end_tss,id_tss,distance_tss,strand_tss,score_tss,context_tss
0,chr1,827380,827380,chr1_827380_827380,125,-,0.186992,antiYR_sameWS,chr1,827505,827505,chr1_827505_827505,245,-,126,-3_AT_-2_-1_TA_0_1_TC_2_c_main_NFR_First_Refer...
1,chr1,827763,827763,chr1_827763_827763,63,+,0.148148,lessDNAencode,chr1,827700,827700,chr1_827700_827700,53,+,66,-3_CG_-2_-1_CG_0_1_TG_2_c_main_NFR_First_Diver...
2,chr1,904146,904146,chr1_904146_904146,291,-,0.125000,sameYR_lowWS,chr1,904437,904437,chr1_904437_904437,3,-,292,-3_AG_-2_-1_CA_0_1_GA_2_c_main_NFR_First_Diver...
3,chr1,904600,904600,chr1_904600_904600,138,+,0.098684,lessDNAencode,chr1,904462,904462,chr1_904462_904462,178,+,132,-3_GC_-2_-1_CA_0_1_GG_2_c_main_NFR_First_Refer...
4,chr1,925528,925528,chr1_925528_925528,75,-,0.096774,lowYR_sameWS,chr1,925603,925603,chr1_925603_925603,9,-,74,-3_GC_-2_-1_TG_0_1_AG_2_c_main_NFR_First_Singl...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45543,chrX,155613122,155613122,chrX_155613122_155613122,142,+,0.000000,sameYR_antiWS,chrX,155612980,155612980,chrX_155612980_155612980,11,+,141,-3_GC_-2_-1_CG_0_1_TG_2_c_main_NFR_Second_Dive...
45544,chrX,155881108,155881108,chrX_155881108_155881108,89,-,0.225000,lessDNAencode,chrX,155881197,155881197,chrX_155881197_155881197,39,-,91,-3_AG_-2_-1_TA_0_1_GT_2_c_main_NFR_First_Diver...
45545,chrX,155881459,155881459,chrX_155881459_155881459,114,+,0.055556,sameYR_lowWS,chrX,155881345,155881345,chrX_155881345_155881345,145,+,116,-3_AG_-2_-1_CG_0_1_GC_2_c_main_NFR_First_Refer...
45546,chrX,155881688,155881688,chrX_155881688_155881688,101,+,0.000000,YRWS,chrX,155881587,155881587,chrX_155881587_155881587,3,+,100,-3_TC_-2_-1_CA_0_1_GT_2_c_main_NFR_First_Diver...
45547,chrX,155959003,155959003,chrX_155959003_155959003,117,-,0.277778,lessDNAencode,chrX,155959120,155959120,chrX_155959120_155959120,5,-,117,-3_GT_-2_-1_TA_0_1_AA_2_c_main_NFR_First_Singl...

In [7]:


#columns 8-13 in df_plustwo are related to +1 nuc (chrom, start, emd, name, score, strand)
colnames = ['chr_plustwo', 'start_plustwo', 'end_plustwo', 'id_plustwo', 'distance_plustwo', 'strand_plustwo', 'score_plustwo', 'context_plustwo', 'chr_plusone', 'start_plusone', 'end_plusone', 'id_plusone', 'score_plusone', 'strand_plusone']
df_plustwo.columns = colnames

df_plustwo

,chr_plustwo,start_plustwo,end_plustwo,id_plustwo,distance_plustwo,strand_plustwo,score_plustwo,context_plustwo,chr_plusone,start_plusone,end_plusone,id_plusone,score_plusone,strand_plusone
0,chr1,827170,827170,chr1_827170_827170,207,-,0.097435,sameYR_lowWS,chr1,827378,827378,chr1_827378_827378,0,-
1,chr1,940660,940660,chr1_940660_940660,166,+,0.136363,sameYR_lowWS,chr1,940493,940493,chr1_940493_940493,0,+
2,chr1,960248,960248,chr1_960248_960248,184,-,0.080460,sameYR_lowWS,chr1,960433,960433,chr1_960433_960433,0,-
3,chr1,999406,999406,chr1_999406_999406,242,-,0.160714,sameYR_lowWS,chr1,999649,999649,chr1_999649_999649,0,-
4,chr1,1020944,1020944,chr1_1020944_1020944,214,+,0.142857,sameYR_lowWS,chr1,1020729,1020729,chr1_1020729_1020729,0,+
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45440,chrX,139932617,139932617,chrX_139932617_139932617,354,-,0.000000,lessDNAencode,chrX,139932972,139932972,chrX_139932972_139932972,0,-
45441,chrX,151397504,151397504,chrX_151397504_151397504,153,+,0.000000,lessDNAencode,chrX,151397350,151397350,chrX_151397350_151397350,0,+
45442,chrX,154371803,154371803,chrX_154371803_154371803,222,+,0.000000,lessDNAencode,chrX,154371580,154371580,chrX_154371580_154371580,0,+
45443,chrX,154411126,154411126,chrX_154411126_154411126,207,-,0.000000,lessDNAencode,chrX,154411334,154411334,chrX_154411334_154411334,0,-
45444,chrX,155070427,155070427,chrX_155070427_155070427,246,-,0.000000,lessDNAencode,chrX,155070674,155070674,chrX_155070674_155070674,0,-

Find the +1: take the difference of start_plusone (in df_plustwo) and start_plusone (in df_set) -> attach the corresponding row to the df_plustwo df

In [8]:
#go through each row in df_plustwo + find the closest row in df_tss_plusone_subset by taking the absolute value of the difference between start_plusone (in df_plustwo) and start_plusone (in df_tss_plusone_subset)
# then add the rest of columns from df_tss_plusone_subset into df_plustwo (of the row of the closest tss)


# Create a list to store the updated rows
updated_rows = []

for _, row in df_plustwo.iterrows():
    # Calculate the absolute difference between start_tss and start_plustwo
    closest_row = df_tss_plusone_subset.loc[
        (df_tss_plusone_subset['start_plusone_adj'] - row['start_plusone']).abs().idxmin()
    ]
    
    # Combine the current row with the closest row's additional columns
    combined_row = row.to_dict()
    for col in df_tss_plusone_subset.columns:
        if col not in df_plustwo.columns:
            combined_row[col] = closest_row[col]
    
    updated_rows.append(combined_row)

# Create a new DataFrame with the updated rows
df_plustwo_updated = pd.DataFrame(updated_rows)

# Optionally, save the updated DataFrame to a file
# df_plustwo_updated.to_csv('updated_df_plustwo.csv', index=False)


df_plustwo_updated

,chr_plustwo,start_plustwo,end_plustwo,id_plustwo,distance_plustwo,strand_plustwo,score_plustwo,context_plustwo,chr_plusone,start_plusone,...,score_plusone_adj,context_plusone_adj,chr_tss,start_tss,end_tss,id_tss,distance_tss,strand_tss,score_tss,context_tss
0,chr1,827170,827170,chr1_827170_827170,207,-,0.097435,sameYR_lowWS,chr1,827378,...,0.186992,antiYR_sameWS,chr1,827505,827505,chr1_827505_827505,245,-,126,-3_AT_-2_-1_TA_0_1_TC_2_c_main_NFR_First_Refer...
1,chr1,940660,940660,chr1_940660_940660,166,+,0.136363,sameYR_lowWS,chr1,940493,...,0.149254,lowYR_sameWS,chr1,940359,940359,chr1_940359_940359,11,+,133,-3_GC_-2_-1_TA_0_1_GC_2_c_main_NFR_First_Singl...
2,chr1,960248,960248,chr1_960248_960248,184,-,0.080460,sameYR_lowWS,chr1,960433,...,0.258065,sameYR_lowWS,chr1,960499,960499,chr1_960499_960499,3,-,65,-3_CG_-2_-1_GA_0_1_TT_2_c_main_NFR_First_Diver...
3,chr1,999406,999406,chr1_999406_999406,242,-,0.160714,sameYR_lowWS,chr1,999649,...,0.051948,YRWS,chr1,1000094,1000094,chr1_1000094_1000094,12,-,444,-3_CG_-2_-1_CG_0_1_GG_2_c_main_NFR_First_Diver...
4,chr1,1020944,1020944,chr1_1020944_1020944,214,+,0.142857,sameYR_lowWS,chr1,1020729,...,0.253522,lowYR_sameWS,chr1,1020120,1020120,chr1_1020120_1020120,84,+,608,-3_TC_-2_-1_CA_0_1_GT_2_c_main_NFR_First_Refer...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45440,chrX,139932617,139932617,chrX_139932617_139932617,354,-,0.000000,lessDNAencode,chrX,139932972,...,0.259259,YRWS,chrX,139933034,139933034,chrX_139933034_139933034,32,-,61,-3_TT_-2_-1_TA_0_1_CA_2_c_main_NFR_First_Diver...
45441,chrX,151397504,151397504,chrX_151397504_151397504,153,+,0.000000,lessDNAencode,chrX,151397350,...,0.256410,sameYR_lowWS,chrX,151397206,151397206,chrX_151397206_151397206,169,+,143,-3_GC_-2_-1_TA_0_1_CT_2_c_main_NFR_First_Refer...
45442,chrX,154371803,154371803,chrX_154371803_154371803,222,+,0.000000,lessDNAencode,chrX,154371580,...,0.344827,YRWS,chrX,154371496,154371496,chrX_154371496_154371496,14,+,83,-3_CC_-2_-1_CA_0_1_CT_2_c_main_NFR_First_Diver...
45443,chrX,154411126,154411126,chrX_154411126_154411126,207,-,0.000000,lessDNAencode,chrX,154411334,...,0.086207,antiYR_sameWS,chrX,154411475,154411475,chrX_154411475_154411475,190,-,140,-3_GG_-2_-1_CA_0_1_GC_2_c_main_NFR_First_Refer...
45444,chrX,155070427,155070427,chrX_155070427_155070427,246,-,0.000000,lessDNAencode,chrX,155070674,...,0.134616,YRWS,chrX,155070850,155070850,chrX_155070850_155070850,9,-,23,-3_CT_-2_-1_CA_0_1_TA_2_c_main_NDR_First_Secon...

Phasing for +2 Nucleosome: take difference between start_Tss and start_plustwo

In [9]:
df_plustwo_updated.columns

Index(['chr_plustwo', 'start_plustwo', 'end_plustwo', 'id_plustwo',
       'distance_plustwo', 'strand_plustwo', 'score_plustwo',
       'context_plustwo', 'chr_plusone', 'start_plusone', 'end_plusone',
       'id_plusone', 'score_plusone', 'strand_plusone', 'start_plusone_adj',
       'end_plusone_adj', 'id_plusone_adj', 'distance_plusone_adj',
       'strand_plusone_adj', 'score_plusone_adj', 'context_plusone_adj',
       'chr_tss', 'start_tss', 'end_tss', 'id_tss', 'distance_tss',
       'strand_tss', 'score_tss', 'context_tss'],
      dtype='object')

In [10]:
# sanity check
# find the absolute difference between start_tss and start_plusone, and see if it matches distance_plusone (in df_plusone_subset)

import pandas as pd

# Assuming df_plusone_subset is already defined
# Example columns: 'start_tss', 'start_plusone', 'distance_plusone'

# Add a new column to indicate whether the condition is met
df_tss_plusone_subset['sanity_check'] = (
    (df_tss_plusone_subset['start_tss'] - df_tss_plusone_subset['start_plusone_adj']).abs()
    == df_tss_plusone_subset['distance_plusone_adj']
)

# Print rows where the sanity check fails
failed_checks = df_tss_plusone_subset[~df_tss_plusone_subset['sanity_check']]
print("Rows where the sanity check failed:")
print(failed_checks)

# Optionally, save the results to a file
# df_plusone_subset.to_csv('sanity_check_results.csv', index=False)

Rows where the sanity check failed:
Empty DataFrame
Columns: [chr_plusone, start_plusone_adj, end_plusone_adj, id_plusone_adj, distance_plusone_adj, strand_plusone_adj, score_plusone_adj, context_plusone_adj, chr_tss, start_tss, end_tss, id_tss, distance_tss, strand_tss, score_tss, context_tss, sanity_check]
Index: []

/tmp/ipykernel_392126/3414515216.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_tss_plusone_subset['sanity_check'] = (

In [11]:
# phasing for +2nucs -> find difference between tss + +2 nuc dyad + create a new column for this + then phase should be the digit in the singles place

df_plustwo_updated['distance_tss_plustwo'] = (
    (df_plustwo_updated['start_tss'] - df_plustwo_updated['start_plustwo']).abs()
)

df_plustwo_updated

# create a new column for phasing
df_plustwo_updated['phasing_plustwo'] = df_plustwo_updated['distance_tss_plustwo'] % 10
df_plustwo_updated

,chr_plustwo,start_plustwo,end_plustwo,id_plustwo,distance_plustwo,strand_plustwo,score_plustwo,context_plustwo,chr_plusone,start_plusone,...,chr_tss,start_tss,end_tss,id_tss,distance_tss,strand_tss,score_tss,context_tss,distance_tss_plustwo,phasing_plustwo
0,chr1,827170,827170,chr1_827170_827170,207,-,0.097435,sameYR_lowWS,chr1,827378,...,chr1,827505,827505,chr1_827505_827505,245,-,126,-3_AT_-2_-1_TA_0_1_TC_2_c_main_NFR_First_Refer...,335,5
1,chr1,940660,940660,chr1_940660_940660,166,+,0.136363,sameYR_lowWS,chr1,940493,...,chr1,940359,940359,chr1_940359_940359,11,+,133,-3_GC_-2_-1_TA_0_1_GC_2_c_main_NFR_First_Singl...,301,1
2,chr1,960248,960248,chr1_960248_960248,184,-,0.080460,sameYR_lowWS,chr1,960433,...,chr1,960499,960499,chr1_960499_960499,3,-,65,-3_CG_-2_-1_GA_0_1_TT_2_c_main_NFR_First_Diver...,251,1
3,chr1,999406,999406,chr1_999406_999406,242,-,0.160714,sameYR_lowWS,chr1,999649,...,chr1,1000094,1000094,chr1_1000094_1000094,12,-,444,-3_CG_-2_-1_CG_0_1_GG_2_c_main_NFR_First_Diver...,688,8
4,chr1,1020944,1020944,chr1_1020944_1020944,214,+,0.142857,sameYR_lowWS,chr1,1020729,...,chr1,1020120,1020120,chr1_1020120_1020120,84,+,608,-3_TC_-2_-1_CA_0_1_GT_2_c_main_NFR_First_Refer...,824,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45440,chrX,139932617,139932617,chrX_139932617_139932617,354,-,0.000000,lessDNAencode,chrX,139932972,...,chrX,139933034,139933034,chrX_139933034_139933034,32,-,61,-3_TT_-2_-1_TA_0_1_CA_2_c_main_NFR_First_Diver...,417,7
45441,chrX,151397504,151397504,chrX_151397504_151397504,153,+,0.000000,lessDNAencode,chrX,151397350,...,chrX,151397206,151397206,chrX_151397206_151397206,169,+,143,-3_GC_-2_-1_TA_0_1_CT_2_c_main_NFR_First_Refer...,298,8
45442,chrX,154371803,154371803,chrX_154371803_154371803,222,+,0.000000,lessDNAencode,chrX,154371580,...,chrX,154371496,154371496,chrX_154371496_154371496,14,+,83,-3_CC_-2_-1_CA_0_1_CT_2_c_main_NFR_First_Diver...,307,7
45443,chrX,154411126,154411126,chrX_154411126_154411126,207,-,0.000000,lessDNAencode,chrX,154411334,...,chrX,154411475,154411475,chrX_154411475_154411475,190,-,140,-3_GG_-2_-1_CA_0_1_GC_2_c_main_NFR_First_Refer...,349,9
45444,chrX,155070427,155070427,chrX_155070427_155070427,246,-,0.000000,lessDNAencode,chrX,155070674,...,chrX,155070850,155070850,chrX_155070850_155070850,9,-,23,-3_CT_-2_-1_CA_0_1_TA_2_c_main_NDR_First_Secon...,423,3

In [12]:
df_plustwo_updated.columns

Index(['chr_plustwo', 'start_plustwo', 'end_plustwo', 'id_plustwo',
       'distance_plustwo', 'strand_plustwo', 'score_plustwo',
       'context_plustwo', 'chr_plusone', 'start_plusone', 'end_plusone',
       'id_plusone', 'score_plusone', 'strand_plusone', 'start_plusone_adj',
       'end_plusone_adj', 'id_plusone_adj', 'distance_plusone_adj',
       'strand_plusone_adj', 'score_plusone_adj', 'context_plusone_adj',
       'chr_tss', 'start_tss', 'end_tss', 'id_tss', 'distance_tss',
       'strand_tss', 'score_tss', 'context_tss', 'distance_tss_plustwo',
       'phasing_plustwo'],
      dtype='object')

In [13]:
df_plustwo_finalized = df_plustwo_updated.drop(columns=['chr_plusone', 'start_plusone', 'end_plusone',
       'id_plusone', 'score_plusone', 'strand_plusone', 'start_plusone_adj',
       'end_plusone_adj', 'id_plusone_adj', 'distance_plusone_adj',
       'strand_plusone_adj', 'score_plusone_adj', 'context_plusone_adj'])
df_plustwo_finalized

,chr_plustwo,start_plustwo,end_plustwo,id_plustwo,distance_plustwo,strand_plustwo,score_plustwo,context_plustwo,chr_tss,start_tss,end_tss,id_tss,distance_tss,strand_tss,score_tss,context_tss,distance_tss_plustwo,phasing_plustwo
0,chr1,827170,827170,chr1_827170_827170,207,-,0.097435,sameYR_lowWS,chr1,827505,827505,chr1_827505_827505,245,-,126,-3_AT_-2_-1_TA_0_1_TC_2_c_main_NFR_First_Refer...,335,5
1,chr1,940660,940660,chr1_940660_940660,166,+,0.136363,sameYR_lowWS,chr1,940359,940359,chr1_940359_940359,11,+,133,-3_GC_-2_-1_TA_0_1_GC_2_c_main_NFR_First_Singl...,301,1
2,chr1,960248,960248,chr1_960248_960248,184,-,0.080460,sameYR_lowWS,chr1,960499,960499,chr1_960499_960499,3,-,65,-3_CG_-2_-1_GA_0_1_TT_2_c_main_NFR_First_Diver...,251,1
3,chr1,999406,999406,chr1_999406_999406,242,-,0.160714,sameYR_lowWS,chr1,1000094,1000094,chr1_1000094_1000094,12,-,444,-3_CG_-2_-1_CG_0_1_GG_2_c_main_NFR_First_Diver...,688,8
4,chr1,1020944,1020944,chr1_1020944_1020944,214,+,0.142857,sameYR_lowWS,chr1,1020120,1020120,chr1_1020120_1020120,84,+,608,-3_TC_-2_-1_CA_0_1_GT_2_c_main_NFR_First_Refer...,824,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45440,chrX,139932617,139932617,chrX_139932617_139932617,354,-,0.000000,lessDNAencode,chrX,139933034,139933034,chrX_139933034_139933034,32,-,61,-3_TT_-2_-1_TA_0_1_CA_2_c_main_NFR_First_Diver...,417,7
45441,chrX,151397504,151397504,chrX_151397504_151397504,153,+,0.000000,lessDNAencode,chrX,151397206,151397206,chrX_151397206_151397206,169,+,143,-3_GC_-2_-1_TA_0_1_CT_2_c_main_NFR_First_Refer...,298,8
45442,chrX,154371803,154371803,chrX_154371803_154371803,222,+,0.000000,lessDNAencode,chrX,154371496,154371496,chrX_154371496_154371496,14,+,83,-3_CC_-2_-1_CA_0_1_CT_2_c_main_NFR_First_Diver...,307,7
45443,chrX,154411126,154411126,chrX_154411126_154411126,207,-,0.000000,lessDNAencode,chrX,154411475,154411475,chrX_154411475_154411475,190,-,140,-3_GG_-2_-1_CA_0_1_GC_2_c_main_NFR_First_Refer...,349,9
45444,chrX,155070427,155070427,chrX_155070427_155070427,246,-,0.000000,lessDNAencode,chrX,155070850,155070850,chrX_155070850_155070850,9,-,23,-3_CT_-2_-1_CA_0_1_TA_2_c_main_NDR_First_Secon...,423,3

In [14]:
#divide df_plustwo_finalized into different dfs based on phasing_plustwo
df_plustwo_phase0 = df_plustwo_finalized[df_plustwo_finalized['phasing_plustwo'] == 0]
df_plustwo_phase1 = df_plustwo_finalized[df_plustwo_finalized['phasing_plustwo'] == 1]
df_plustwo_phase2 = df_plustwo_finalized[df_plustwo_finalized['phasing_plustwo'] == 2]
df_plustwo_phase3 = df_plustwo_finalized[df_plustwo_finalized['phasing_plustwo'] == 3]
df_plustwo_phase4 = df_plustwo_finalized[df_plustwo_finalized['phasing_plustwo'] == 4]
df_plustwo_phase5 = df_plustwo_finalized[df_plustwo_finalized['phasing_plustwo'] == 5]
df_plustwo_phase6 = df_plustwo_finalized[df_plustwo_finalized['phasing_plustwo'] == 6]
df_plustwo_phase7 = df_plustwo_finalized[df_plustwo_finalized['phasing_plustwo'] == 7]
df_plustwo_phase8 = df_plustwo_finalized[df_plustwo_finalized['phasing_plustwo'] == 8]
df_plustwo_phase9 = df_plustwo_finalized[df_plustwo_finalized['phasing_plustwo'] == 9]

# save each df as a separate bed file (tab-separated) and put it in /home/ubuntu/honors_research/peak_align/reference_files/+2_Nuc_References
df_plustwo_phase0.to_csv("/home/ubuntu/honors_research/peak_align/reference_files/+2_Nuc_References/+2_phase0.bed", sep = "\t", index = False, header = False)
df_plustwo_phase1.to_csv("/home/ubuntu/honors_research/peak_align/reference_files/+2_Nuc_References/+2_phase1.bed", sep = "\t", index = False, header = False)
df_plustwo_phase2.to_csv("/home/ubuntu/honors_research/peak_align/reference_files/+2_Nuc_References/+2_phase2.bed", sep = "\t", index = False, header = False)
df_plustwo_phase3.to_csv("/home/ubuntu/honors_research/peak_align/reference_files/+2_Nuc_References/+2_phase3.bed", sep = "\t", index = False, header = False)
df_plustwo_phase4.to_csv("/home/ubuntu/honors_research/peak_align/reference_files/+2_Nuc_References/+2_phase4.bed", sep = "\t", index = False, header = False)
df_plustwo_phase5.to_csv("/home/ubuntu/honors_research/peak_align/reference_files/+2_Nuc_References/+2_phase5.bed", sep = "\t", index = False, header = False)
df_plustwo_phase6.to_csv("/home/ubuntu/honors_research/peak_align/reference_files/+2_Nuc_References/+2_phase6.bed", sep = "\t", index = False, header = False)
df_plustwo_phase7.to_csv("/home/ubuntu/honors_research/peak_align/reference_files/+2_Nuc_References/+2_phase7.bed", sep = "\t", index = False, header = False)
df_plustwo_phase8.to_csv("/home/ubuntu/honors_research/peak_align/reference_files/+2_Nuc_References/+2_phase8.bed", sep = "\t", index = False, header = False)
df_plustwo_phase9.to_csv("/home/ubuntu/honors_research/peak_align/reference_files/+2_Nuc_References/+2_phase9.bed", sep = "\t", index = False, header = False)

In [15]:
df_tss_plusone_subset.columns

Index(['chr_plusone', 'start_plusone_adj', 'end_plusone_adj', 'id_plusone_adj',
       'distance_plusone_adj', 'strand_plusone_adj', 'score_plusone_adj',
       'context_plusone_adj', 'chr_tss', 'start_tss', 'end_tss', 'id_tss',
       'distance_tss', 'strand_tss', 'score_tss', 'context_tss',
       'sanity_check'],
      dtype='object')

In [16]:
# +1 nucleosomes

df_tss_plusone_subset['phasing_plusone'] = df_tss_plusone_subset['distance_plusone_adj'] % 10
df_tss_plusone_subset.drop(columns=['chr_tss', 'start_tss', 'end_tss', 'id_tss', 'distance_tss', 'strand_tss', 'score_tss', 'context_tss', 'sanity_check'], inplace=True)

/tmp/ipykernel_392126/1458701884.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_tss_plusone_subset['phasing_plusone'] = df_tss_plusone_subset['distance_plusone_adj'] % 10
/tmp/ipykernel_392126/1458701884.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_tss_plusone_subset.drop(columns=['chr_tss', 'start_tss', 'end_tss', 'id_tss', 'distance_tss', 'strand_tss', 'score_tss', 'context_tss', 'sanity_check'], inplace=True)

In [17]:
df_tss_plusone_subset

,chr_plusone,start_plusone_adj,end_plusone_adj,id_plusone_adj,distance_plusone_adj,strand_plusone_adj,score_plusone_adj,context_plusone_adj,phasing_plusone
0,chr1,827380,827380,chr1_827380_827380,125,-,0.186992,antiYR_sameWS,5
1,chr1,827763,827763,chr1_827763_827763,63,+,0.148148,lessDNAencode,3
2,chr1,904146,904146,chr1_904146_904146,291,-,0.125000,sameYR_lowWS,1
3,chr1,904600,904600,chr1_904600_904600,138,+,0.098684,lessDNAencode,8
4,chr1,925528,925528,chr1_925528_925528,75,-,0.096774,lowYR_sameWS,5
...,...,...,...,...,...,...,...,...,...
45543,chrX,155613122,155613122,chrX_155613122_155613122,142,+,0.000000,sameYR_antiWS,2
45544,chrX,155881108,155881108,chrX_155881108_155881108,89,-,0.225000,lessDNAencode,9
45545,chrX,155881459,155881459,chrX_155881459_155881459,114,+,0.055556,sameYR_lowWS,4
45546,chrX,155881688,155881688,chrX_155881688_155881688,101,+,0.000000,YRWS,1
45547,chrX,155959003,155959003,chrX_155959003_155959003,117,-,0.277778,lessDNAencode,7

In [18]:

#divide df_tss_plusone_subset into different dfs based on phasing_plusone
df_plusone_phase0 = df_tss_plusone_subset[df_tss_plusone_subset['phasing_plusone'] == 0]
df_plusone_phase1 = df_tss_plusone_subset[df_tss_plusone_subset['phasing_plusone'] == 1]
df_plusone_phase2 = df_tss_plusone_subset[df_tss_plusone_subset['phasing_plusone'] == 2]
df_plusone_phase3 = df_tss_plusone_subset[df_tss_plusone_subset['phasing_plusone'] == 3]
df_plusone_phase4 = df_tss_plusone_subset[df_tss_plusone_subset['phasing_plusone'] == 4]
df_plusone_phase5 = df_tss_plusone_subset[df_tss_plusone_subset['phasing_plusone'] == 5]
df_plusone_phase6 = df_tss_plusone_subset[df_tss_plusone_subset['phasing_plusone'] == 6]
df_plusone_phase7 = df_tss_plusone_subset[df_tss_plusone_subset['phasing_plusone'] == 7]
df_plusone_phase8 = df_tss_plusone_subset[df_tss_plusone_subset['phasing_plusone'] == 8]
df_plusone_phase9 = df_tss_plusone_subset[df_tss_plusone_subset['phasing_plusone'] == 9]

# save each df as a separate bed file (tab-separated) and put it in /home/ubuntu/honors_research/peak_align/reference_files/+1_Nuc_References

df_plusone_phase0.to_csv("/home/ubuntu/honors_research/peak_align/reference_files/+1_Nuc_References/+1_phase0.bed", sep = "\t", index = False, header = False)
df_plusone_phase1.to_csv("/home/ubuntu/honors_research/peak_align/reference_files/+1_Nuc_References/+1_phase1.bed", sep = "\t", index = False, header = False)
df_plusone_phase2.to_csv("/home/ubuntu/honors_research/peak_align/reference_files/+1_Nuc_References/+1_phase2.bed", sep = "\t", index = False, header = False)
df_plusone_phase3.to_csv("/home/ubuntu/honors_research/peak_align/reference_files/+1_Nuc_References/+1_phase3.bed", sep = "\t", index = False, header = False)
df_plusone_phase4.to_csv("/home/ubuntu/honors_research/peak_align/reference_files/+1_Nuc_References/+1_phase4.bed", sep = "\t", index = False, header = False)
df_plusone_phase5.to_csv("/home/ubuntu/honors_research/peak_align/reference_files/+1_Nuc_References/+1_phase5.bed", sep = "\t", index = False, header = False)
df_plusone_phase6.to_csv("/home/ubuntu/honors_research/peak_align/reference_files/+1_Nuc_References/+1_phase6.bed", sep = "\t", index = False, header = False)
df_plusone_phase7.to_csv("/home/ubuntu/honors_research/peak_align/reference_files/+1_Nuc_References/+1_phase7.bed", sep = "\t", index = False, header = False)
df_plusone_phase8.to_csv("/home/ubuntu/honors_research/peak_align/reference_files/+1_Nuc_References/+1_phase8.bed", sep = "\t", index = False, header = False)
df_plusone_phase9.to_csv("/home/ubuntu/honors_research/peak_align/reference_files/+1_Nuc_References/+1_phase9.bed", sep = "\t", index = False, header = False)